### PR TITLE
Always add resource folders with optional attribute

### PR DESCRIPTION
**Pull request by laeubi**
Resource folders should be handled like a source folder that is always added with optional=true (even if the folder is not present yet) so they appear in the project as soon as they are created.

Fix https://github.com/eclipse-m2e/m2e-core/issues/1353

### CODE REVIEW

**Review by HannesWell — APPROVED** [review]
Sounds reasonable, but this creates new test-failures, that have to be fixed.

**Comment by laeubi** [comment]
As a first step I now have split a change that allows to perform an more weak assert, this should hopefully not fail any test but is required to prepare test adjustments:
- https://github.com/eclipse-m2e/m2e-core/pull/1355

**Comment by laeubi** [comment]
Alright this already lowered the failure count but still things left... will check that.

**Comment by laeubi** [comment]
There is one test left that do not fails because of the classpath order:

`org.eclipse.m2e.tests.BuildPathManagerTest.test431080_flatDirectoryLayout()`

this one is a bit tricky, because currently the resourcefolder is silently skipped (as it does not exits), no it is added leading to
grafik

configuring this to the basedir (like the others as well) seems make it being ignored by **maven**
grafik

so it seems such a "flat" layout is actually not very well supported (I think @fbricon have already mentioned this), also importing the project leads to very strange behavior, in contrast to having the project root a new folder is created that is the full path of the project on disk (what is empty) like here:
grafik

So for me it seems the test is already broken by design and we probably should `@Ignore` it (+create an issue about supporting flat layouts) unless we have a good idea how to support such flat layouts, from a first though about this it seems to me that in such a case we should simply just have one source folder that points to the project root and skip all additional source and resource folders ... but thats something I defiantly not plan to implement in this PR...

**Comment by HannesWell** [comment]
> 
> So for me it seems the test is already broken by design and we probably should `@Ignore` it (+create an issue about supporting flat layouts) unless we have a good idea how to support such flat layouts, from a first though about this it seems to me that in such a case we should simply just have one source folder that points to the project root and skip all additional source and resource folders ... but thats something I defiantly not plan to implement in this PR...

Sounds good 👍🏽

**Pull request merged**
