### PR TITLE
Limit LSP4E dependency to version <= 0.23 due to the API--breaking ch…

### PR DESCRIPTION
**Pull request by vrubezhny**
…anges

### CODE REVIEW

**Comment by laeubi** [comment]
why not update m2e to the latest changes and raise the **lower** version?

**Comment by vrubezhny** [comment]
> why not update m2e to the latest changes and raise the **lower** version?

When a user having 2.3.0 installed updates to the latest lsp4e snapshot (which is allowed due to no restriction exists) - he/she gets broken lemminx editor.  

Imho, better is to restrict m3e 2.3.x  to `o.e.lsp4e` v.<=0.17 (which all should be API compatible) and then start updating m2e 2.4.x to the latest changes rising the lower version as you suggest.

**Comment by vrubezhny** [comment]
@akurtakov @laeubi OK. I got your point. So, this PR is to be canceled. 

Sticking to providing the changes need to fix API incompatibility and limiting `lower` `o.e.lsp4e` version to be `0.17`.

**Comment by laeubi** [comment]
Just from OSGi POV it would be much better if LSP4j would version the packages using [semantic-versioning](https://docs.osgi.org/whitepaper/semantic-versioning/) and m2e would import-package the used API with consumer-range, that way there is much less problems in that area.

Depending on how lsp4j is build it would also good to use the new tycho-basline plugin to ensure API compatibility on the package level.

**Comment by vrubezhny** [comment]
Closing this PR in favor of #1407

**Pull request closed without merging**
