### PR TITLE
Remove all indexer

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by fbricon** [comment]
This is a breaking change (JBoss Tools depends on the Indexer API), you should update m2e version to 2.0 and advertise it on the mailing list(s). 

cc @jeffmaury

**Comment by mickaelistria** [comment]
OK

**Comment by laeubi** [comment]
If we have breaking changes / m2e 2.0 we should also consider removing deprecated APIs.

**Comment by mickaelistria** [comment]
> If we have breaking changes / m2e 2.0 we should also consider removing deprecated APIs.

Yes, I'd like to prepare this work but wait a bit before we merge it. I hope we can release a newer m2e with various improvements in the next week or the week after, then we can start a break-fest.

**Comment by HannesWell** [comment]
> > If we have breaking changes / m2e 2.0 we should also consider removing deprecated APIs.
> 
> Yes, I'd like to prepare this work but wait a bit before we merge it. I hope we can release a newer m2e with various improvements in the next week or the week after, then we can start a break-fest.

That's reasonable. We should announce the breaking changes respectively version 2.0 as early as possible and give the community some time to react.

**Comment by claudioweiler** [comment]
Hi @mickaelistria, everyone!

This also removed capability of using internal maven archetypes.

Any workaround, or plugin that solves this?

**Comment by mickaelistria** [comment]
Can you please open an issue about this failing functionality?

**Comment by claudioweiler** [comment]
@mickaelistria , I don't know it this a "failing functionality".

Nexus Indexer was able to find archetypes deployed on internal services (e.g. JFrog Artifactory) and show them in new maven projects wizard.

I found a way to upload a manually generated `archetype-catalog.xml` to Artifactory, them added a remote catalog (Preferences > Maven > Archetypes).

This solved as workaround, but manually generating `archetype-catalog.xml` is no good. Maybe Sonatype Nexus handles this, but Artifactory not.

References:

- https://jfrog.atlassian.net/browse/RTFACT-15719?jql=text%20~%20%22archetype-catalog.xml%22
- https://stackoverflow.com/questions/1039752/artifactory-auto-generate-archetype-catalog

**Pull request merged**
