### PR TITLE
Enable dependabot

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
@HannesWell @laeubi This has the potential to generate some churn short term but is really good for every project longterm. Please merge or close depending on how you feel about it.

**Comment by laeubi** [comment]
I would be fine with it...

**Review by laeubi — APPROVED** [review]

**Review by HannesWell — APPROVED** [review]
I appreciate tooling support for version updates.
Even more would I support dependabot support for the target file, but I know that is a known issue. :)

**Comment by akurtakov** [comment]
So let's get the party started.

**Comment by akurtakov** [comment]
Unfortunately this didn't work out. See https://github.com/eclipse-m2e/m2e-core/network/updates/520025626 :
```
Dependabot requires a pom.xml to evaluate your Java dependencies. It had expected to find one at the path: /target-platform/pom.xml.

If this isn't a Java project, you may wish to disable updates for it in the .github/dependabot.yml config file in this repo.
```

**Comment by laeubi** [comment]
AFAIK dependabot do not support polyglot-builds, so it can only look at items from the root pom.xml files.

**Pull request merged**
