### PR TITLE
[RelEng] Let Tycho build a self-contained p2-repo with minimal content

### PR DESCRIPTION
**Pull request by HannesWell**
In the first build I just want to test [tycho-p2-repository-plugin#includeAllSources](https://tycho.eclipseprojects.io/doc/master/tycho-p2/tycho-p2-repository-plugin/assemble-repository-mojo.html#includeAllSources), which IIRC hat some issues a while ago.

If that works the next step is to use [includeAllDependencies](https://tycho.eclipseprojects.io/doc/master/tycho-p2/tycho-p2-repository-plugin/assemble-repository-mojo.html#includeAllDependencies) together with [filterProvided](https://tycho.eclipseprojects.io/doc/master/tycho-p2/tycho-p2-repository-plugin/assemble-repository-mojo.html#filterProvided), introduced in https://github.com/eclipse-tycho/tycho/pull/2028.

@laeubi FYI

### CODE REVIEW

**Comment by HannesWell** [comment]
Stage one word well, now lets try stage two.

**Comment by mickaelistria** [comment]
Note that this can also later allow to get rid of source features.

**Comment by HannesWell** [comment]
@laeubi currently this fails with:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project org.eclipse.m2e.repository: Execution default-assemble-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository failed. UnsupportedOperationException -> [Help 1]
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project org.eclipse.m2e.repository: Execution default-assemble-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository failed.
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke (Method.java:568)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
 Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-assemble-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository failed.
     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke (Method.java:568)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
 Caused by: java.lang.UnsupportedOperationException
     at java.util.Collections$UnmodifiableCollection.removeIf (Collections.java:1096)
     at org.eclipse.tycho.p2tools.TychoMirrorApplication.collectUnits (TychoMirrorApplication.java:217)
     at org.eclipse.tycho.p2tools.copiedfromp2.MirrorApplication.run (MirrorApplication.java:222)
     at org.eclipse.tycho.p2tools.MirrorApplicationServiceImpl.mirrorReactor (MirrorApplicationServiceImpl.java:183)
     at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:234)
     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke (Method.java:568)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by laeubi** [comment]
I created:
- https://github.com/eclipse-tycho/tycho/pull/2036

**Comment by HannesWell** [comment]
The build succeeds, but the created p2-repo only contains the `slf4j.api.source_1.7.36.jar` but not the main artifact.
Besides that the created repo looks good. I just noticed that there are many org.eclipse.wst.* plugins in in it, which reminds me of https://github.com/eclipse-m2e/m2e-core/issues/1248.

**Comment by HannesWell** [comment]
Besides that `org.yaml.snakeyaml_1.27.0.v20221112-0806.jar` and its source bundle made it into the location of the `https://download.eclipse.org/wildwebdeveloper/releases/1.0.1/` repo, which is also referenced.
But looking at its plugin folder I cannot find there, so maybe it is referenced there as well?

**Comment by laeubi** [comment]
> The build succeeds, but the created p2-repo only contains the slf4j.api.source_1.7.36.jar but not the main artifact.

As we are most likely not building slf4j.api there is no main artifact, the jar itself might be already included in some referenced repo then.

**Comment by HannesWell** [comment]
> > The build succeeds, but the created p2-repo only contains the slf4j.api.source_1.7.36.jar but not the main artifact.
> 
> As we are most likely not building slf4j.api there is no main artifact, the jar itself might be already included in some referenced repo then.

AFAICT  the referenced repos only contain the slf4j-api bundle in an older version and even with another BSN.
IMHO an artifact should only be left out if the referenced repo contains that artifact with the exact same BSN and version. Otherwise a p2-repo cannot contain newer artifacts e.g. fetched from Maven-Central.

**Comment by laeubi** [comment]
If you think there is a bug please try providing a reproducer :-)
The BSN actually don't matter as P2 do not know anything about that, P2 only knows IU ID + Version ... so if any repository contains the API bundle with the same IU ID+Version it is removed.

**Comment by HannesWell** [comment]
Using the [new possibilities of Tycho's p2-repository-plugin](https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#new-parameter-for-tycho-p2-repository-pluginassemble-repository) look very promising and the result does very good so far.

Two things that I noticed:
For `com.google.guava.source_32.0.1.jre` and `jakarta.servlet-api.source_5.0.0` only the source jars are included.
I doubt that the main jar is included in any of the referenced p2 repos since guava 32 is quite new.
`m2e.maven.runtime` is also happy with older guava versions, which are provided by other p2-repos, I guess that this could be the reason?
My first assumption about how this would work was that Tycho first computes the set of artifacts like when building a self-contained repo and then remove those artifacts that are contained in a p2-repo that is available for reference (in exactly the version that would have been in a physically self-contained one).

**Comment by laeubi** [comment]
You can look at `org.eclipse.tycho.p2tools.TychoMirrorApplication.collectUnits(IQueryable<IInstallableUnit>, IProgressMonitor)` if you are interested in the details, there are two steps:

1. A slice is created, in this phase all items are collected and probably sources are included
2. Then the units are collected, while collecting removes all units that are present in any referenced repository using `IInstallableUnit#equals` where the default implementations uses id and version equals.

currently there is no debug output but you can put a breakpoint in the remove method triggered on `true` to find out what repository contains the units already.

**Comment by HannesWell** [comment]
Now that Tycho 4.0.3 is available we can finally use this.
I checked the result and everything is expected, we have the fully dependency closure available in the m2e-repo but keep the repository at a minimal size since references to all p2-repos in the TP are added automatically and artifacts provided there are removed and at the same time unnecessary references are not added. The Orbit repo is explicitly excluded from being added as reference.

**Pull request merged**
