### PR TITLE
m2e feature is incomplete #180

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <christoph@laeubi-soft.de>

### CODE REVIEW

**Comment by mickaelistria** [comment]
p2 is supposed to resolve dependencies from Import-Package. What's the benefit of adding transitive deps in the feature.xml ?

**Comment by laeubi** [comment]
Maybe one can use P2 in that way, but in general this will not happen:

1. Eclipse PDE Product launch will complain about missing requirements
2. Tycho will either complain or build an incomplete product (depend on the type of missing features)
3. Update-sites will simply miss additional features (even if included the required **bundles**)

So for sure if you just install m2e into an existing eclipse and allows to pull in everything from everywhere it might work, but adding the feature m2e-core for example is not enough as transitive dependent features/bundles are not declared and need to be provided by hand.

And even though it seems hard to declare everything, that's how it is supposed to work. The feature.xml and its dependencies are the counterpart of the MANIFEST.MF and its declared dependencies for a bundle (e.g. if your bundle does not declare it requires DS it will happily install but most ptobably not fulfill the desired work).

The problem is, that most features are not crafted very well and the tool-support is bad (e.g. there is no validate-feature button afaik) but to the bottom line a feature should be self-contained that if I install it either everything is well defined (include) or declared (required) as a dependency so it could be looked up in the local or remotes.

**Comment by mickaelistria** [comment]
> Eclipse PDE Product launch will complain about missing requirements

Is there a bug open to PDE on this topic (transitive deps not resolved on product launch)?

> Tycho will either complain or build an incomplete product (depend on the type of missing features)

That's surprising as Tycho does dependency resolution using p2. I think it's a bug in Tycho and should be reported and fixed there.

> a feature should be self-contained

So why not including all platform artifacts in it as well? Since inception of p2, a feature is just a "top-level" IU that's not a bundle and that allows to list a consistent set of bundles to provide some support for X or Y, it's not really intended to list all the transitive dependencies required to work.

**Comment by laeubi** [comment]
> Is there a bug open to PDE

This is not a bug

> I think it's a bug in Tycho

Not really, a product is not required to contain everything as one can install (optional) components later on, beside that there is a validate-product goal if you don't like that feature (as well as PDE allwos you to still launch such a product)

> So why not including all platform artifacts in it as well?

In general, m2e should have one feature-dependecy to `eclipse-jdt` (don't know if there is actually such a single feature so from now on let us assume these features exits) and that's enough for the basics as `eclipse-jdt` should (transitively) include everything that's required there (e.g. platform itself), and one for each other not maintained feature (e.g `maven-embedded` might be such a feature, or `lemmix-xml-editor`) and include all m2e bundles that make up "the-core" or are not part of any stand-alone feature (e.g. google-guava, apache-common...).

So if all features are well defined, it is enough to create an **empty**, feature-based product and just add m2e core to get a full running ide with JDT+m2e that could be build/run right away!

Now we have the m2e-pde feature, that would have a requirement to `m2e-core` and `eclipse-pde`, if we use that (or install it later) our IDE will get JDT+PDE+m2e

**Comment by mickaelistria** [comment]
> This is not a bug

Yet it's something that cause issue and push the need fo workarounds in
other places.

> Not really, a product is not required to contain everything as one can
install (optional) components later on

As far as I understand, we're not talking about optional componentsin this
PR, but of full requirements that are already explicited in MANIFEST.MF,
hence why the redundancy?

> In general, m2e should have one feature-dependecy to eclipse-jdt (don't
know if there is actually such a single feature so from now on let us
assume these features exits) and that's enough for the basics as
eclipse-jdt should (transitively) include everything that's required there
(e.g. platform itself), and one for each other not maintained feature (e.g
maven-embedded might be such a feature, or lemmix-xml-editor) and include
all m2e bundles that make up "the-core" or are not part of any stand-alone
feature (e.g. google-guava, apache-common...).
>
> So if all features are well defined, it is enough to create an empty,
feature-based product and just add m2e core to get a full running ide with
JDT+m2e that could be build/run right away!
>
> Now we have the m2e-pde feature, that would have a requirement to
m2e-core and eclipse-pde, if we use that (or install it later) our IDE will
get JDT+PDE+m2e

I don't get the relationship with this PR.
Also, I believe you miss the history behind p2: what you suggest is almost
exactly how things worked before p2, with features that were expected to be
perfectly defined, include all dependencies and so on. The result was
horrible: features were rarely correct, installing a feature required lots
of documentation reading, and then a lot of troubleshooting to find out the
missing dependency and so on. Basically, this illustrates that any strategy
that assume features are perfectly defined is doomed to failure; and that
we should rely on p2 for this kind of stuff.

**Comment by laeubi** [comment]
A product (or OSGi runtime) is not required to include everything that is declared in the manifest. That's a common misunderstanding, OSGi allows installing thinks that are not yet fully satisfied (bundles, configuration, services). That's why a product, even though not all included bundles are fully satisfied, is valid and could be useful.

Having features that describe 'useful configurations' is very common even outside eclipse, every package-manager works that way (declaring whats required, whats optional and even whats recommend), Apache Karaf also has a much more straight feature-model that allows people to define good features even with configurations. Having a feature just for the sake of bundling some useful bundles is a really poor model...

If you say 'how things worked before p2' i can only repeat that maybe P2 was meant to solve such issues but obviously either is not integrated into the eclipse-eco system until now or does a bad job.

Just try out the example described above, empty feature based product, add m2e feature to it and it will fail in all cases (tycho, pde-launch, product export). Even adding 'obvious' dependencies like platform does not solve the issue... even adding "add required" makes the story even worse as it adds arbitrary features (some would call them useless ones), and still not ending with a valid product.

**Pull request closed without merging**
