### PR TITLE
LemMinX-Maven 0.10.1 + Lemminx 0.27.0 + WWD 1.3.0

### PR DESCRIPTION
**Pull request by vrubezhny**

### CODE REVIEW

**Comment by vrubezhny** [comment]
JUnit test `org.eclipse.m2e.editor.lemminx.tests.EditorTest.testOpenChildThenParentResolvesParent` is excluded due to known problem in Lemminx-Maven v.0.10.0

**Comment by laeubi** [comment]
@vrubezhny you marked this a WIP what needs to be done here before it can be merged?

**Comment by HannesWell** [comment]
> @vrubezhny you marked this a WIP what needs to be done here before it can be merged?

Looks like there used to be some test-failures, but now the build is green. Mac currently always fails.

**Comment by vrubezhny** [comment]
@laeubi @HannesWell  There were m2e Editor failures due to the recent changes in Lemminx and Lemminx-maven extension. Now the JUnit tests pass with success (even for the failing MacOS runner).
 
So I would merge the PR and after that we're waiting a m2e-core version to be promoted to SimRel.
Thank you!

**Review by HannesWell — APPROVED** [review]
Looks good thank you.


> So I would merge the PR and after that we're waiting a m2e-core version to be promoted to SimRel.

I plan to do some more changes at the Weekend and will probably after the weekend contribute a fixed M3 snapshot to SimRel.

**Pull request merged**
