### PR TITLE
[TP] update to Eclipse 4.31 and latest versions of other dependencies

### PR DESCRIPTION
**Pull request by HannesWell**

### CODE REVIEW

**Comment by akurtakov** [comment]
Jenkins shows 1 failing test: [org.eclipse.m2e.core.ui.tests.ConsoleTest.testConsole_debuggerAttachmentAndLinkAlignmentAndBehavior_tychoProject](https://ci.eclipse.org/m2e/job/m2e/job/PR-1720/9/testReport/org.eclipse.m2e.core.ui.tests/ConsoleTest/testConsole_debuggerAttachmentAndLinkAlignmentAndBehavior_tychoProject/) and same one fails on master thus merging.

**Comment by akurtakov** [comment]
Ah, ConsoleTest sysouts have to be removed before merging. Would you please do so? Having same build environment as local one would help as there would be less unneeded differences.

**Comment by HannesWell** [comment]
> Ah, ConsoleTest sysouts have to be removed before merging. Would you please do so? Having same build environment as local one would help as there would be less unneeded differences.

Done. Thanks for paying attention to that detail.

**Comment by HannesWell** [comment]
> Jenkins shows 1 failing test: [org.eclipse.m2e.core.ui.tests.ConsoleTest.testConsole_debuggerAttachmentAndLinkAlignmentAndBehavior_tychoProject](https://ci.eclipse.org/m2e/job/m2e/job/PR-1720/9/testReport/org.eclipse.m2e.core.ui.tests/ConsoleTest/testConsole_debuggerAttachmentAndLinkAlignmentAndBehavior_tychoProject/) and same one fails on master thus merging.

I cannot reproduce any of the test-failures on my Windows computer. I'll continue to submit this since I don't think any of them are critical. Will investigate them later.

**Pull request merged**
