### PR TITLE
Add support for classifiers to pde + urlhandler

### PR DESCRIPTION
**Pull request by laeubi**
This adds the ability to use classifiers in the mvn-url handler as well as the target-ui

### CODE REVIEW

**Comment by mickaelistria** [comment]
I don't know if it's related but there is 1 more test failing with this patch: https://ci.eclipse.org/m2e/job/m2e/view/change-requests/job/PR-38/3/testReport/junit/org.eclipse.m2e.editor.xml/MissingSchemaMarkerTest/testMissingSchemaMarker/ can you please check if it could be related? I've restarted a build of master in the meantime to see whether the issue occurs there too.

**Comment by laeubi** [comment]
Can't see any relation with my changes, [the test](https://github.com/tesla/m2e-core-tests/blob/966dff8dd21bb54a43ca936c917f8138ee8275d9/org.eclipse.m2e.editor.xml.tests/src/org/eclipse/m2e/editor/xml/MissingSchemaMarkerTest.java) seems to check that there is a marker for a missing schema, copies a "good" pom over and then checks that the marker is gone but nothing related to any target stuff afaiks.

**Comment by laeubi** [comment]
Test is still failing :-\
Any idea how we could proceed here? As there are other tests failing too, what is the reason there? Timing? Maybe a similar issue here. I don't know if it is feasible but might it be an option on the long term to move to RCPTT tests for the UI parts instead? That would allow to execute tests in a "visual" way and might be a lot easier to see then whats going on.

**Comment by laeubi** [comment]
@mickaelistria can you trigger a new build? I have checked that for a fresh PR currently only the three tests fail. I still can't get a reason why this PR should fail the test, it only adds one new field to the Editor /parsing one additional String and all those code should never be called in the current test-suite.

**Comment by laeubi** [comment]
I have now also added support for including the source into the target:
grafik

**Comment by laeubi** [comment]
@mickaelistria I have done the following:

1. clone the m2e-core-test repo
2. started an eclipse with the changes from my branch
3. imported the project of the test that fails

I can see the warning marker is there see screenshot
grafik

if I copy pom_good.xml to pom.xml the marker goes away. So it seems to me that the test should work from what I understand.

**Comment by mickaelistria** [comment]
Have you tried running the test suite locally?

**Comment by laeubi** [comment]
I have run the failing test-case manually to see if I find a clue why it is not working but everything works as expected,

Also local execution of that test yields a successful result:

```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.951 s - in org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest
testMissingSchemaMarker(org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest)  Time elapsed: 5.467 s

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by mickaelistria** [comment]
Let's try rebasing in case that helps.
Also, please try the full test suite; it could be that 1 other test gets affected by that change and cascade to some effect on that one. By the way, the log shows sme data at https://ci.eclipse.org/m2e/job/m2e/view/change-requests/job/PR-41/lastSuccessfulBuild/artifact/m2e-core-tests/org.eclipse.m2e.tests/target/work/data/.metadata/.log , anything interesting?

**Comment by laeubi** [comment]
Running the full suite gives me the 3 "known failures", I'll try to create a fresh PR anway...

```
Failures: 
  FileCompletionTest.testFilesAndDirsCompletion:104 expected:<2> but was:<6>
  FileCompletionTest.testModuleCompletion:73 expected:<2> but was:<3>

Tests run: 46, Failures: 2, Errors: 0, Skipped: 0

Errors: 
  BuildPathManagerTest.testDownloadSources_006_nonMavenProject:657 » Core Reinde...
```

The Build-log shows a lot of exceptions but I can't judge if the are expected (seems ecf cant handle 301 redirects properly) at least I can't find anything I can correlate with any code changes :-\

**Comment by laeubi** [comment]
See https://github.com/eclipse-m2e/m2e-core/pull/43

**Pull request closed without merging**
