### PR TITLE
[cleanup] erefactor/EclipseJdt - Remove redundant semicolons

### PR DESCRIPTION
**Pull request by cal101**
EclipseJdt cleanup 'RemoveRedundantSemicolons' applied by erefactor.

For EclipseJdt see https://www.eclipse.org/eclipse/news/4.19/jdt.php
For erefactor see https://github.com/cal101/erefactor

Signed-off-by: Carsten Heyl <cal-1@web.de>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thanks. I've created https://github.com/eclipse-m2e/m2e-core/pull/79 which aggregates all those cleanup changes and fix the version as requested in https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md#%EF%B8%8F-version-bump . Next time, please try building locally and fix versions as reported in the build before submitting a PR.

**Comment by laeubi** [comment]
@mickaelistria for me this looks like an automated bot that does not knows about version changes and so on :-)

**Comment by cal101** [comment]
Hi!

No bot yet ;-)
I am the author of the backing pipeline and it took quite some time to get it running with m2e because the existing instructions just didn't work for me.
It was not clear to me that the versions always need to be bumped, I will fix that.
The pipeline does run the tests automatically but I disabled the version check because even when executing the statements from the CONTRIBUTING page manually, they just don't work for me.
From what I understand from your comments:
I should be possible to
1. checkout the repo
2. set PATH to OpenJDK 11
3. Execute the commands from CONTRIBUTING
and should be green?

**Comment by cal101** [comment]
Just tell me how you would like it to be organized and I am willing/trying to adjust.

**Comment by mickaelistria** [comment]
Merged as part of https://github.com/eclipse-m2e/m2e-core/pull/79 , thanks!

**Pull request closed without merging**
