### PR TITLE
[Console] add link to project-pom at project headline in build printout

### PR DESCRIPTION
**Pull request by HannesWell**
This PR has the goal to add a link in a project's build print-out _headline_ that when being activated opens the projects `pom.xml` file in the standard editor.

If a user clicks on `org.eclipse.m2e.tests.projects:simpleProjectWithJUnit5Test` the POM-editor opens displaying the project's pom:

grafik

### CODE REVIEW

**Comment by HannesWell** [comment]
What could be also handy is to place a link to the last project build in case of a build failure:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.307 s
[INFO] Finished at: 2022-01-31T22:27:07+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project simpleProjectWithJUnit5Test: There are test failures.
```

The link could then be placed at `on project **simpleProjectWithJUnit5Test**`.

What do you think about the links showed above and the suggested link for failures.

**Comment by mickaelistria** [comment]
That's a nice addition, however, tests are failing at the moment.

**Comment by HannesWell** [comment]
> That's a nice addition, however, tests are failing at the moment.

Thank you. I just fixed the failures.

With the latest commits I also added another link in case of a build failure to open the pom of the failed project. So there are two new links now.

grafik

**Comment by HannesWell** [comment]
With this this, for me this change is complete.
If there are no objections I will merge this tomorrow.

**Pull request merged**
