### PR TITLE
Upgrade to latest PDE API Enhancements #115

### PR DESCRIPTION
**Pull request by laeubi**
See #115 and https://github.com/eclipse-m2e/m2e-core/pull/34 for more details.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Root pom.xml needs to update
```xml
    <eclipse.stream>2020-12</eclipse.stream>
    <eclipse-repo.url>https://download.eclipse.org/eclipse/updates/4.18/</eclipse-repo.url>
    <eclipse-simrel.url>https://download.eclipse.org/releases/${eclipse.stream}</eclipse-simrel.url>
```

**Comment by mickaelistria** [comment]
I trust you about the code, and build looks fine.
My only question is about the added icons. Aren't there the `@2x` version somewhere? Those icons will most likely look ugly on high resolution screens without the @2x (not a blocker).

**Comment by laeubi** [comment]
I'll check for the @2x icons. On the long term it might be worth if we can have an m2e.icons bundle I think or can adapt to platform-images the main problem seems that plugin.xml does not support url references.
I'll also make some more testing with the changed version the next days.

**Comment by mickaelistria** [comment]
Any news about @2x & png icons?

**Comment by laeubi** [comment]
I'm currently try to get these merge conflict resolved due to "automatic code cleanup" :-(

**Comment by laeubi** [comment]
I hopefulyl have resolved any coflics and added x2 icons when available.

**Pull request merged**
