### PR TITLE
Build with eclipse-jarsigner-plugin 1.3.2

### PR DESCRIPTION
**Pull request by HannesWell**

### CODE REVIEW

**Comment by HannesWell** [comment]
Reported the failure of the eclipse-jarsigner-plugin to:
https://github.com/eclipse-cbi/org.eclipse.cbi/issues/182

**Comment by mbarbero** [comment]
That's very strange. I've restarted the signing service, would you mind giving it another try? Thanks!

**Comment by mickaelistria** [comment]
Retried as requested, still failing: https://ci.eclipse.org/m2e/job/m2e/job/PR-901/3/console

**Comment by HannesWell** [comment]
> That's very strange. I've restarted the signing service, would you mind giving it another try? Thanks!

I want to add, that with 1.3.1 the signing works fine, therefore I'm not sure if this is caused by the signing service?

**Comment by laeubi** [comment]
I have replayed the job with `-e` so we maybe better see whats going on ...

**Comment by laeubi** [comment]
Okay the plugin is not very informative here or the real cause is supressed:

```
[ERROR] Failed to execute goal org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.3.2:sign (sign) on project org.eclipse.m2e.maven.runtime: [Mon Sep 12 08:41:30 UTC 2022] Failed to sign jar file '/home/jenkins/agent/workspace/m2e_PR-901/m2e-maven-runtime/org.eclipse.m2e.maven.runtime/target/org.eclipse.m2e.maven.runtime-3.8.601-SNAPSHOT.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.3.2:sign (sign) on project org.eclipse.m2e.maven.runtime: [Mon Sep 12 08:41:30 UTC 2022] Failed to sign jar file '/home/jenkins/agent/workspace/m2e_PR-901/m2e-maven-runtime/org.eclipse.m2e.maven.runtime/target/org.eclipse.m2e.maven.runtime-3.8.601-SNAPSHOT.jar
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:306)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:577)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: [Mon Sep 12 08:41:30 UTC 2022] Failed to sign jar file '/home/jenkins/agent/workspace/m2e_PR-901/m2e-maven-runtime/org.eclipse.m2e.maven.runtime/target/org.eclipse.m2e.maven.runtime-3.8.601-SNAPSHOT.jar
    at org.eclipse.cbi.maven.ExceptionHandler.handleError (ExceptionHandler.java:32)
    at org.eclipse.cbi.maven.plugins.jarsigner.mojo.SignMojo.signArtifact (SignMojo.java:370)
    at org.eclipse.cbi.maven.plugins.jarsigner.mojo.SignMojo.signArtifact (SignMojo.java:351)
    at org.eclipse.cbi.maven.plugins.jarsigner.mojo.SignMojo.execute (SignMojo.java:326)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:577)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by HannesWell** [comment]
> Okay the plugin is not very informative here or the real cause is supressed:
> 
Unfortunately not. It's the same as reported in https://github.com/eclipse-cbi/org.eclipse.cbi/issues/182.

**Comment by mbarbero** [comment]
I've pushed a fix and it is deployed as version `1.3.3-SNAPSHOT`. Please give it a try. If it works, I'll publish a new release.

**Comment by HannesWell** [comment]
> I've pushed a fix and it is deployed as version `1.3.3-SNAPSHOT`. Please give it a try. If it works, I'll publish a new release.

That snapshot looks good. All builds pass now. Thank you.
Let me know when you have released 1.3.3.

**Comment by mbarbero** [comment]
1.3.3 has been released.

**Pull request merged**
