### PR TITLE
WIP Jdt use diamond operator clean up 3

### PR DESCRIPTION
**Pull request by cal101**

### CODE REVIEW

**Comment by mickaelistria** [comment]
1 extra test seems to be constantly failing with this PR.

**Comment by cal101** [comment]
Interesting, the pipeline ci tests passes. I take a look.
It would be easier to notice real problems if the jenkins test would pass for current master.

**Comment by cal101** [comment]
I now see that one test from https://github.com/tesla/m2e-core-tests.git fails. I didn't integrated that into the pipeline CI tests yet.
Continuing investigation ...

**Comment by cal101** [comment]
Same test is failing in https://github.com/eclipse-m2e/m2e-core/pull/86 but not in master.
Perhaps a flaky test?
No success in reproducing it locally yet.

**Comment by mickaelistria** [comment]
Those commits need to be rebased to workaround the version issue happening on CI (we're in one of the rare case when this issue may happen because of numerous commits merged in some random-ish order). Can you please rebase and then `git push --force` to your fork branch?

**Comment by cal101** [comment]
I don't understand if that is also related to the failing of the extra test.
I am not able to reproduce that locally.
But nevertheless I re-create and split this change up into small pieces and will add PRs for all of them.
This way jenkins shall tell us if and which part triggers the extra test failing.

**Pull request merged**
