### PR TITLE
[TP] Update to WWD 1.3.4 and LSP4E 0.26

### PR DESCRIPTION
**Pull request by HannesWell**
Fixes https://github.com/eclipse-m2e/m2e-core/issues/1751

### CODE REVIEW

**Comment by HannesWell** [comment]
Build fails with 
```
Error:  Cannot resolve target definition:
Error:    Software being installed: org.eclipse.wildwebdeveloper.xml.feature.feature.group 1.3.2.202403191205
Error:    Missing requirement: org.eclipse.lsp4e 0.18.7.202404031149 requires 'osgi.bundle; org.eclipse.mylyn.wikitext 3.0.40' but it could not be found
Error:    Missing requirement: org.eclipse.lsp4e 0.18.8.202404261614 requires 'osgi.bundle; org.eclipse.mylyn.wikitext 3.0.40' but it could not be found
Error:    Cannot satisfy dependency: org.eclipse.wildwebdeveloper.xml 1.3.2.202403191205 depends on: osgi.bundle; org.eclipse.lsp4e 0.16.0
Error:    Cannot satisfy dependency: org.eclipse.wildwebdeveloper.xml.feature.feature.group 1.3.2.202403191205 depends on: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper.xml [1.3.2.202403191205,1.3.2.202403191205]
```

Altough `org.eclipse.mylyn.wikitext` is available, in version `3.0.44.202211082139` but I don't see a fixed range.
Furthermore I wonder why there are two versions of lsp4e?

**Comment by HannesWell** [comment]
Altough I have changed the pipelines with use Java-21 the build fails as follows:
```
[INFO] Resolving file:${project_loc:/m2e-core}/target-platform/m2e-runtimes.target
[INFO] Reading target platform file:/home/jenkins/agent/workspace/m2e_PR-1753/target-platform/m2e-runtimes.target
[INFO] Performing subquery
[ERROR] org.eclipse.wildwebdeveloper.xml 1.3.2.202403191205 requires Execution Environment that matches (&(osgi.ee=JavaSE)(version=21)) but the current resolution context uses [a.jre.javase 17.0.0]
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.wildwebdeveloper.xml.feature.feature.group 1.3.2.202403191205
[ERROR]   Missing requirement: org.eclipse.wildwebdeveloper.xml 1.3.2.202403191205 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=21))' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.wildwebdeveloper.xml.feature.feature.group 1.3.2.202403191205 depends on: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper.xml 
```

@laeubi or @merks any immediate idea? I haven't yet investigated it in great detail.

**Comment by akurtakov** [comment]
You have to change targetJRE to Java 21 in target file too.

**Comment by merks** [comment]
This worked for me:

image

**Comment by HannesWell** [comment]
> You have to change targetJRE to Java 21 in target file too.

🤦🏽‍♂️Obviously. Thanks, that worked locally. 

> This worked for me:

Thanks for that hint, but this is not set in m2e's pom.xml.

**Comment by HannesWell** [comment]
@laeubi any objections against building with 21? Actually we have no other option.

**Comment by akurtakov** [comment]
IMO even M2E should move to Java 21 now.

**Comment by HannesWell** [comment]
The build succeeded now and the test failures are unrelated, so lets submit this.

> IMO even M2E should move to target Java 21 now.

In general I have no objects about that, but I currently don't have the time to change all the configurations.
Therefore my suggestion is to such change in the beginning of the next development cycle.

**Comment by laeubi** [comment]
> IMO even M2E should move to target Java 21 now.

This will require that EPPs (and consequently Eclipse SDK) move to Java 21 I just wanted to mention it.

**Comment by akurtakov** [comment]
> > IMO even M2E should move to target Java 21 now.
> 
> This will require that EPPs (and consequently Eclipse SDK) move to Java 21 I just wanted to mention it.

EPPs already made the move - https://github.com/eclipse-packaging/packages/issues/130

**Pull request merged**
