### PR TITLE
Remove Depprecated MavenRuntimeManager and deprecated methods

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by laeubi** [comment]
The problem is that there are test referencing this, I'm currently struggling a bit with that :-)

**Comment by mickaelistria** [comment]
If those tests are not relevant to m2e's functionaliy, then you can just remove them.

**Comment by HannesWell** [comment]
Thanks for starting the removal of deprecated elements.

If I searched right, there are many more deprecated elements to remove.
Should we create a dedicated issue to track the progress of the removal (IIRC there was only a discussion)? And do you plan to remove the remaining elements too?

**Comment by mickaelistria** [comment]
Was merged as https://github.com/eclipse-m2e/m2e-core/commit/fee4e7aea7e47a6152cf8c385cb829ec98af6c53

**Pull request closed without merging**
