### PR TITLE
[PDE] update to biz.aQute.bndlib 6.0.0 and include biz.aQute.bnd.util

### PR DESCRIPTION
**Pull request by HannesWell**
This is a follow-up for #356 that performs the update to `biz.aQute.bndlib 6.0.0` in a controlled fashion and adds the now required `biz.aQute.bnd.util` to the TP and the `m2e.pde.feature`.

This change should solve issue #348 .

### CODE REVIEW

**Comment by laeubi** [comment]
> Ok. Correct me if I'm wrong, but as far as I can see it, there are no tests for the Maven-locations in m2e yet.

BTW if you are interested I can share some targets I use for testing the maven-locations, but I have no idea how to create an automated test-case for this from the UI perspective it must be something like this:

1. open a specific target file and wait until it is resolved (or error if not)
2. set it as Active Target and wait for completion
3. check in Target Platform State that certain bundles are available

For some features one also wants to check that the target *not* resolves but the error feedback is  very poor in PDE so I have no idea if this can be reliable be checked.

**Comment by mickaelistria** [comment]
Testing UI is hard, but testing target platform resolution/loading/content is possible with the org.eclipse.pde.core.target.LoadTargetDefinitionJob and TargetPlatformService.

**Comment by HannesWell** [comment]
I recently created some tests in PDE that involved the target-platform, so I can try to create some tests for it in the next days.
Test-cases where you specify a target file as input and check if the resolved TP contains the expected bundles/features (and maybe some more metadata) would be ideal IMO.
Checking errors might be a bit more complicated, but I'll see.

But as Micakel said: those tests would not test the UI/the editors, just the functionality of the targets. But I think that is nevertheless important.

**Comment by laeubi** [comment]
@HannesWell what you think, should we make this ready? A new release is already out and I don't see a reason to delay this more...

**Comment by mickaelistria** [comment]
A CQ in not necessary, the https://github.com/eclipse/dash-licenses/ tool does approve this content without need for further IP review.

**Comment by HannesWell** [comment]
> A CQ in not necessary, the https://github.com/eclipse/dash-licenses/ tool does approve this content without need for further IP review.

Thank you Mickael for the hint! I tried the `dash-licenses` tool by myself and can confirm that it approves the content.
I created a basic pom.xml that has the following dependencies:
```
<dependency>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>biz.aQute.bndlib</artifactId>
	<version>6.0.0</version>
	<type>jar</type>
</dependency>
<dependency>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>biz.aQute.bnd.util</artifactId>
	<version>6.0.0</version>
	<type>jar</type>
</dependency>
```
And otherwise the default setup from the dash-licenses' ReadMe.
For the record, print out was:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< de.wellmann:test.dash-tool >---------------------
[INFO] Building test.dash-tool 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- license-tool-plugin:0.0.1-SNAPSHOT:license-check (license-check) @ test.dash-tool ---
[INFO] Querying Eclipse Foundation for license data for 3 items.
[INFO] Found 1 items.
[INFO] Querying ClearlyDefined for license data for 2 items.
[INFO] Found 2 items.
[INFO] Vetted license information was found for all content. No further investigation is required.
[INFO] Summary file was written to: C:\dev\workspaces\eclipse.m2e\test.dash-tool\target\dash\summary
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.165 s
[INFO] Finished at: 2021-12-10T18:38:56+01:00
[INFO] ------------------------------------------------------------------------
```
And the content of the summary was:
```
maven/mavencentral/biz.aQute.bnd/biz.aQute.bnd.util/6.0.0, Apache-2.0 OR EPL-2.0, approved, clearlydefined
maven/mavencentral/biz.aQute.bnd/biz.aQute.bndlib/6.0.0, Apache-2.0 OR EPL-2.0, approved, clearlydefined
maven/mavencentral/org.slf4j/slf4j-api/1.7.25, MIT, approved, CQ13368
```
So this is ready to go.

**Comment by HannesWell** [comment]
I also checked the IP-clearance of `biz.aQute.bndlib` and `biz.aQute.bnd.util` version 6.1.0 this morning.
First it failed with missing approvals, but about an hour later I ran it again and the check then succeeded. 
The clearlydefined-website shows that the entry was just updated shortly after my query:
https://clearlydefined.io/definitions/maven/mavencentral/biz.aQute.bnd/biz.aQute.bnd.util/6.1.0

Was this coincidence or can a failed query trigger a check at clearlydefined?

**Comment by HannesWell** [comment]
But even though we have IP-clearance `biz.aQute.bndlib` and `biz.aQute.bnd.util` version 6.1.0 cannot be used now, because they besides others require the following OSGi-packages:
- org.osgi.util.function version 1.2.0
- org.osgi.util.promise 1.2.0
- org.osgi.service.repository 1.1.0
But Equinox contains the first two only in version 1.1.0 respectively 1.1.1. (in the bundle `org.eclipse.osgi.util`). The latter seems not to be included in Equinox at all (at least I could not find it in the rt.equinox repos).

I don't expect it will be problematic to update `org.osgi.util.function` and `org.osgi.util.promise`, but I'm not sure about service.repository.
So for now I think we have to go with version 6.0.0, because I think we should not include thise bundles into m2e.

**Comment by HannesWell** [comment]
Jenkins build passed. I'm going to merge.

**Comment by mickaelistria** [comment]
> First it failed with missing approvals, but about an hour later I ran it again and the check then succeeded.
> The clearlydefined-website shows that the entry was just updated shortly after my query:
> https://clearlydefined.io/definitions/maven/mavencentral/biz.aQute.bnd/biz.aQute.bnd.util/6.1.0
> Was this coincidence or can a failed query trigger a check at clearlydefined?

I had similar experiences. I don't know the answer, but I've now adopted a strategy of "I'll try again later" before opening a CQ or Eclipse IP request, and it usually succeeds. It could be that ClearlyDefined prioritize review of content that got requested.

**Pull request merged**
