### PR TITLE
Switch to tycho-build extension

### PR DESCRIPTION
**Pull request by akurtakov**
Instead of the deprecated tycho-pomless one.

### CODE REVIEW

**Comment by akurtakov** [comment]
@HannesWell @laeubi Any idea why the build is broken ?

**Comment by laeubi** [comment]
m2e currently uses the "maven mode" of tycho that is not supported by the tycho-build extension, I think we decided to rework that due to recent enhancements in m2e+tycho but it got a bit forgotten ...

**Comment by akurtakov** [comment]
So the change should happen on m2e or on tycho side?

**Comment by laeubi** [comment]
m2e needs to change here, but this might reveal some tasks for tycho as well (e.g. if there is something that can not be done).

**Comment by HannesWell** [comment]
It is exactly as Christoph said. I started the work here https://github.com/eclipse-m2e/m2e-core/pull/466 but got distracted by other things in the meantime. I'll try to push that up in my list.
But at the moment I'm slowed down since I catched Covid as souvenir from my vacation and have to get well first.

**Comment by akurtakov** [comment]
Fast recovery, Hannes!

**Comment by HannesWell** [comment]
> Fast recovery, Hannes!

Thank you. :)

**Comment by akurtakov** [comment]
Closing this one as there is further work to be done before that's feasible

**Pull request closed without merging**
