### PR TITLE
AbstractJavaProjectConfigurator: Fix NPE if EE has no compliance options

### LINKED ISSUE #1735: NPE in AbstractJavaProjectConfigurator
Steps to reproduce:

- install Eclipse 4.32M1 and m2e - https://download.eclipse.org/eclipse/downloads/drops4/S-4.32M1-202404061800/
- try to import https://github.com/eclipse-m2e/m2e-core/tree/master/org.eclipse.m2e.jdt.tests/projects/compilerSettings

m2e throws NPE at AbstractJavaProjectConfigurator.java, line 128, and the project isn't configured correctly.
The issue is caused by https://github.com/eclipse-equinox/equinox/issues/571

### PR DESCRIPTION
**Pull request by sratz**
Fixes #1735.

### CODE REVIEW

**Review by HannesWell — COMMENTED** [review]
Thanks Sebastian for this. 
In general it looks good, but I would like to take this as an opportunity to replace var by the actual type in the changed code and to remove the `JRE` element from the `supportedEETypes` set.

**Comment by andi-huber** [comment]
Thanks Sebastian, patch works for me  (Eclipse 4.32M1). You saved my day.

**Comment by sratz** [comment]
> Thanks Sebastian for this. In general it looks good, but I would like to take this as an opportunity to replace var by the actual type in the changed code

Done.

> Furthermore the service version of `org.eclipse.m2e.jdt` needs a (+100) bump and probably the feature as well.

I bumped the jdt plugin and features where it is included by +100. Can you double-check?

> and to remove the `JRE` element from the `supportedEETypes` set.

Hmm, shouldn't this be done in a different change/PR to keep the bugfix minimal?

**Comment by sratz** [comment]
> Thanks for the update! I fixed the accidental removal of imports which lead to compilation errors.

Thanks! Weird, I have no idea how that removed import slipped in :D

> > > and to remove the `JRE` element from the `supportedEETypes` set.
> > 
> > 
> > Hmm, shouldn't this be done in a different change/PR to keep the bugfix minimal?
> 
> That's also fine, see #1739 :)

👍

**Comment by HannesWell** [comment]
> > Thanks for the update! I fixed the accidental removal of imports which lead to compilation errors.
> 
> Thanks! Weird, I have no idea how that removed import slipped in :D

That can happen. Maybe your local m2e.maven.runtime had errors and then JDT decided to remove the imports.

Anyway now it's fixed. Thanks again.

**Pull request merged**
