### PR TITLE
Bug 570473: M2e Plugins still uses low resolution icons

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Please amend you commit to add the Signed-Off-By footer.

**Comment by BeckerWdf** [comment]
> Please amend you commit to add the Signed-Off-By footer.

I pushed an ammend with the footer to my clone of the repo. How do I get this into this PR?

**Comment by mickaelistria** [comment]
`push --force` was the right thing to do ;)

**Comment by BeckerWdf** [comment]
@mickaelistria: Could you perform a manual test of my change and take care for merging?

**Comment by mickaelistria** [comment]
I'll just merge now, let snapshots build and will test using that snapshot build next time my IDE wants to update.

**Pull request merged**
