### PR TITLE
Remove unused code, or code which is could be substituted with JDK calls

### PR DESCRIPTION
**Pull request by gzsombor**

### CODE REVIEW

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md#%EF%B8%8F-version-bump . Can you please update the versions as suggested by the documentation and build?

**Comment by gzsombor** [comment]
I hope, I've modified the correct numbers.

**Comment by gzsombor** [comment]
Now, it failed with one test ( https://ci.eclipse.org/m2e/job/m2e/job/PR-302/2/testReport/ ), but that test also fail on the master branch too - https://ci.eclipse.org/m2e/job/m2e/job/master/56/testReport/

**Comment by mickaelistria** [comment]
Thanks. This test failure is not related (it's about #284 and others).
So the patch is all good, I'm merging it, thanks!

**Comment by gzsombor** [comment]
Thanks for the quick merge!

**Pull request merged**
