### PR TITLE
Provide existing launch configs as shortcuts

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
Thanks for trying it out, I couldn't really find anything how this is supposed to work, even though it is implemented by some platform items, I can try to improve the platform code if you think it should work as you have described here...

**Comment by laeubi** [comment]
Some finding: Hovering the arrow of the "Run" buttons in the toolbar calls that method to compute a tooltip ....

**Comment by laeubi** [comment]
And a waring to people like me that always forget about that: Never put a breakpoint into menu code :-1:

**Comment by laeubi** [comment]
I now created a PR to make the items available here:
- https://github.com/eclipse-platform/eclipse.platform.debug/pull/122

If this is merged, we can finally implement this in a way that for older eclipse it shows a dialog and for newer eclipse shows the actual shortcuts.

**Comment by laeubi** [comment]
This now looks like this:
grafik

**Comment by laeubi** [comment]
I created a followup here but from m2e side this is done now:
- https://github.com/eclipse-platform/eclipse.platform.debug/pull/164

**Comment by mickaelistria** [comment]
Thanks!

**Pull request merged**
