### PR TITLE
Test the tests

### PR DESCRIPTION
**Pull request by laeubi**
To test:
- https://github.com/tesla/m2e-core-tests/pull/166

### CODE REVIEW

**Comment by laeubi** [comment]
Eclipse infra down https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1390

**Comment by HannesWell** [comment]
> Eclipse infra down https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1390

Looks like the infra is back and there are only two test failures.

**Comment by HannesWell** [comment]
And thanks for working on the mavenarchiver tests. :)

**Comment by HannesWell** [comment]
I think this can be closed.
The tests in question are merged and they are also tested and fixed in https://github.com/eclipse-m2e/m2e-core/pull/820.

**Pull request closed without merging**
