### PR TITLE
Add advanced editing capabilities based on upcoming PDE API

### PR DESCRIPTION
**Pull request by laeubi**
This shows the new features that would be possible once the [advanced PDE API](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568865) is available.

It is possible to select an item and exclude it from the target resolution (e.g. one wants to exclude a dependency that is not a bundle, an older version or similar)
grafik
 
of course it is possible to include the item afterwards again.

It is now also possible to edit individual items and edit the instructions for this particular item
grafik

This also includes some more enhancements, e.g. if the clipboard contains a maven-dependency-xml fragment and a new item is added, the GAV fields are automatically filled.

### CODE REVIEW

**Comment by akurtakov** [comment]
What is the status of this PR?

**Comment by laeubi** [comment]
@akurtakov I assume that this PR needs to wait for the next release of PDE, then I need to update it to reflect latest code changes.

**Comment by akurtakov** [comment]
If there is not gonna be m2e release prior to the March Platform release, m2e can build against and require latest PDE. @mickaelistria wdyt?

**Comment by mickaelistria** [comment]
I think it's better to leave room for a potential release before March.

**Comment by laeubi** [comment]
This is not crucial so I think its fine to wait until the next PDE release.

**Comment by mickaelistria** [comment]
Should this be revived?

**Comment by laeubi** [comment]
Yep I'll try to update the PR base don latest API.

**Comment by laeubi** [comment]
The source has just diverged too much in the meantime so I decided to create a new on top of current master see: https://github.com/eclipse-m2e/m2e-core/pull/121

**Pull request closed without merging**
