### PR TITLE
Reference Eclipse Platform repo

### PR DESCRIPTION
**Pull request by mickaelistria**
To resolve JDT in case it's missing

### CODE REVIEW

**Comment by HannesWell** [comment]
When the latest repository is referenced, future updates of old releases may not work because they only refer to the then latest repo and not to the repo current at the time when the repo was created.

**Comment by mickaelistria** [comment]
I'm torn here, as it's usually a good thing to move towards newer release of dependencies...

**Comment by HannesWell** [comment]
> I'm torn here, as it's usually a good thing to move towards newer release of dependencies...

Fully agree and I also try to use the latest dependencies if possible. But I think it should happen in a controlled manner.
And has the potential to create some hard to predict/understand behavior that might de-facto break repositories that just worked, without changing them.

**Comment by laeubi** [comment]
I wonder if we could add some magic to tycho that would simply add [the locations from the target](https://github.com/eclipse-m2e/m2e-core/blob/master/target-platform/target-platform.target)... that way we don't need to manage this at two locations.

Or[ if PDE would support variables](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578430) we could define them in the pom.xml properties and have only placeholders.

**Comment by HannesWell** [comment]
> I wonder if we could add some magic to tycho that would simply add [the locations from the target](https://github.com/eclipse-m2e/m2e-core/blob/master/target-platform/target-platform.target)... that way we don't need to manage this at two locations.
> 
> Or[ if PDE would support variables](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578430) we could define them in the pom.xml properties and have only placeholders.

These are two ideas I also had already and I expect to be very helpful in scenarios like this one!
Is there already an issue for Tycho where it can be discussed?

**Pull request merged**
