### PR TITLE
Fix classpath for a maven project with multiple compile executions

### PR DESCRIPTION
**Pull request by snjeza**
Fixes https://github.com/eclipse-m2e/m2e-core/issues/246 - The tool didn't
generate the correct classpath for a maven project with multiple compile executions

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

### CODE REVIEW

**Review by mickaelistria — CHANGES_REQUESTED** [review]
Can you please
* Move the test to the org.eclipse.m2e.jdt.tests plugin
* Reduce the test to the very minimal content to reproduce the initial issue
* Rewrite commit message into something that describes more precisely the issue that's fixed
?

**Comment by mickaelistria** [comment]
Please bump modified bundles/features version.

**Comment by snjeza** [comment]
> Please bump modified bundles/features version.

Done.

**Comment by mickaelistria** [comment]
Thanks!

**Pull request merged**
