### PR TITLE
Build with Maven 3.9.9 on Jenkins and in GH workflow

### PR DESCRIPTION
**Pull request by HannesWell**

### CODE REVIEW

**Comment by HannesWell** [comment]
Looks like Maven 3.9.9 is not yet available in EF-Jenkins. Keep this open until it is available.

**Comment by HannesWell** [comment]
Also added the change to `ubunut-latest` images in the Jenkins pipeline, but somehow Jenkins is waiting for an executor forever...

**Comment by akurtakov** [comment]
Requested adding ubuntu-latest image to m2e JIPP via https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5050

**Comment by akurtakov** [comment]
Test failures unrelated to the changes.

**Pull request merged**
