### PR TITLE
Import Maven Projects wizard does not sort projects

### PR DESCRIPTION
**Pull request by ThomasReinhardt**
fix for #1840

### CODE REVIEW

**Comment by akurtakov** [comment]
ECA still not good https://api.eclipse.org/git/eca/status/gh/eclipse-m2e/m2e-core/1850

**Comment by ThomasReinhardt** [comment]
@akurtakov my ECA is sorted out but there is a test error complaining about "Missing completion proposals". Is that my fault? I don't think it is but I don't know for sure.

**Comment by akurtakov** [comment]
This is unstable test.

**Comment by ThomasReinhardt** [comment]
Am I supposed to do anything about that unstable test?

**Comment by akurtakov** [comment]
Thanks for the patch. It is all good!

**Pull request merged**
