### PR TITLE
Include sources of m2e.workspace.cli and strengthen its referencing

### PR DESCRIPTION
**Pull request by HannesWell**
This PR adds the sources of `org.eclipse.m2e.workspace.cli` which was the only bundle in the m2e-repo for which no sources where provided. The reason was that the build failed when its sources were added, but it turned out this was only due to a missing qualifier update of the `m2e.feature`. Originally I suspected that it was because its sources were not properly jar-singed but that was not the case, they are.

To enforce the qualifier update I did not use a `forceQualifierUpdate.txt` but just strengthened the reference to `m2e.workspace.cli`. Since this is code in a plug-in contained in the m2e.feature that causes the required qualifier-update too.

### CODE REVIEW

**Comment by HannesWell** [comment]
There is also an update to `org.eclipse.m2e.workspace.cli` version `0.4.0` available.
I think the only relevant change is:
https://github.com/eclipse-m2e/org.eclipse.m2e.workspace/commit/109c865aa819045397886dda5d791d0384af7e2f#diff-30aacdd0821b7681ee971c9324b3e785ad6b1a692079db2d3ebb6cfd03f5bc10

Since `WorkspaceState` and `MutableWorkspaceState` are also used in m2e this change could affect m2e.
Does anybody know if we can simply change to WorkspaceState2?

**Comment by HannesWell** [comment]
OK it looks like it was not only the qualifier update:
```
[INFO] --- tycho-p2-repository-plugin:2.6.0:verify-repository (verify) @ org.eclipse.m2e.site ---
[INFO] Verifying p2 repositories in /home/jenkins/agent/workspace/m2e_PR-533/org.eclipse.m2e.site/target/repository
[ERROR] Problems downloading artifact: osgi.bundle,org.eclipse.m2e.workspace.cli.source,0.3.1.
[ERROR]   File has invalid content:/tmp/signatureFile6983768633477971670.jar
[ERROR]     Invalid content:META-INF/ECLIPSE_.RSA: META-INF/ECLIPSE_.RSA
org.eclipse.osgi.signedcontent.InvalidContentException: META-INF/ECLIPSE_.RSA
    at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.getSignedEntries (SignedContentFromBundleFile.java:243)
    at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.<init> (SignedContentFromBundleFile.java:192)
    at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent (SignedBundleHook.java:170)
    at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verifyContent (SignatureVerifier.java:84)
    at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verify (SignatureVerifier.java:66)
    at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.close (SignatureVerifier.java:115)
    at org.eclipse.equinox.internal.provisional.p2.artifact.repository.processing.ProcessingStep.close (ProcessingStep.java:92)
    at org.eclipse.equinox.internal.p2.artifact.processors.checksum.MessageDigestProcessingStep.close (MessageDigestProcessingStep.java:58)
    at org.eclipse.equinox.internal.provisional.p2.artifact.repository.processing.ProcessingStep.close (ProcessingStep.java:92)
    at org.eclipse.equinox.internal.p2.artifact.processors.checksum.MessageDigestProcessingStep.close (MessageDigestProcessingStep.java:58)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.reportStatus (SimpleArtifactRepository.java:1273)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact (SimpleArtifactRepository.java:665)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact (SimpleArtifactRepository.java:796)
    at org.eclipse.tycho.p2.tools.verifier.VerifierServiceImpl.verifyArtifactContent (VerifierServiceImpl.java:118)
    at org.eclipse.tycho.p2.tools.verifier.VerifierServiceImpl.verifyAllArtifactContent (VerifierServiceImpl.java:110)
    at org.eclipse.tycho.p2.tools.verifier.VerifierServiceImpl.verify (VerifierServiceImpl.java:62)
    at org.eclipse.tycho.plugins.p2.repository.VerifyIntegrityRepositoryMojo.execute (VerifyIntegrityRepositoryMojo.java:52)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at sun.security.util.SignatureFileVerifier.processImpl (SignatureFileVerifier.java:317)
    at sun.security.util.SignatureFileVerifier.process (SignatureFileVerifier.java:259)
    at java.util.jar.JarVerifier.processEntry (JarVerifier.java:316)
    at java.util.jar.JarVerifier.update (JarVerifier.java:230)
    at java.util.jar.JarInputStream.read (JarInputStream.java:212)
    at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.getSignedEntries (SignedContentFromBundleFile.java:227)
    at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.<init> (SignedContentFromBundleFile.java:192)
    at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent (SignedBundleHook.java:170)
    at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verifyContent (SignatureVerifier.java:84)
    at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verify (SignatureVerifier.java:66)
    at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.close (SignatureVerifier.java:115)
    at org.eclipse.equinox.internal.provisional.p2.artifact.repository.processing.ProcessingStep.close (ProcessingStep.java:92)
    at org.eclipse.equinox.internal.p2.artifact.processors.checksum.MessageDigestProcessingStep.close (MessageDigestProcessingStep.java:58)
    at org.eclipse.equinox.internal.provisional.p2.artifact.repository.processing.ProcessingStep.close (ProcessingStep.java:92)
    at org.eclipse.equinox.internal.p2.artifact.processors.checksum.MessageDigestProcessingStep.close (MessageDigestProcessingStep.java:58)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.reportStatus (SimpleArtifactRepository.java:1273)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact (SimpleArtifactRepository.java:665)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact (SimpleArtifactRepository.java:796)
    at org.eclipse.tycho.p2.tools.verifier.VerifierServiceImpl.verifyArtifactContent (VerifierServiceImpl.java:118)
    at org.eclipse.tycho.p2.tools.verifier.VerifierServiceImpl.verifyAllArtifactContent (VerifierServiceImpl.java:110)
    at org.eclipse.tycho.p2.tools.verifier.VerifierServiceImpl.verify (VerifierServiceImpl.java:62)
    at org.eclipse.tycho.plugins.p2.repository.VerifyIntegrityRepositoryMojo.execute (VerifyIntegrityRepositoryMojo.java:52)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
```
@mickaelistria, @laeubi can this be handled in m2e or has `m2e.workspace.cli` to be adjusted?

**Comment by laeubi** [comment]
> There is also an update

7 (!) years ago o_O

If m2e-core requires m2e.workspace, won't it make sense to merge it then into m2e-core? I don't see any value in a dedicated project that do not had any activity since 7 years and this effort is better placed in integrating it here.

**Comment by HannesWell** [comment]
> > There is also an update
> 
> 7 (!) years ago o_O
> 
Yep. That was the reason that made me wonder if this is incompatible or there is another reason why it should not be used.

> If m2e-core requires m2e.workspace, won't it make sense to merge it then into m2e-core? I don't see any value in a dedicated project that do not had any activity since 7 years and this effort is better placed in integrating it here.

The same question came to my mind and I think one reason is that it is deployed to Maven-Central under io.takari's group id:
https://mvnrepository.com/artifact/io.takari.m2e.workspace/org.eclipse.m2e.workspace.cli/0.4.0

If it would be merged into m2e-core we would have to deploy to Maven-Central too (it is currently consumed by four other takari plug-ins that seem to be active) but we would likely have to change the groupId.

**Comment by laeubi** [comment]
I think we don't need to deploy it per-se to maven central the other takari plugins can still use this for historic reasons and I think we can for sure change the group-id then.

Anyways my plan is to make tycho capable to also deploy to maven-repository and make those artifacts easy consumable again by maven, so maybe sonner or late it will again approach then under a new group-id.

**Comment by laeubi** [comment]
By the way this would be a good opportunity to simply throw away the deprecated code and start fresh ;-)

Of course we could also think about making an own implementation of the Workspace reader that is more specific to m2e and drop the takari stuff. There is really not much to to for m2e and we already have a view of the workspace projects so the implementation cost would be low.

**Comment by HannesWell** [comment]
> I think we don't need to deploy it per-se to maven central the other takari plugins can still use this for historic reasons and I think we can for sure change the group-id then.
> 
I have no opinion on that but I'm also not affected. I just wanted to add the sources for the sake of completeness and simplicity of the build. :)

> Anyways my plan is to make tycho capable to also deploy to maven-repository and make those artifacts easy consumable again by maven, so maybe sonner or late it will again approach then under a new group-id.

Sounds good 👍🏽 

> By the way this would be a good opportunity to simply throw away the deprecated code and start fresh ;-)
> 
This change or the major version jump to m2e 2.0.0? If we do that, I think we should do it with m2e 2.0.0 to have a clean transition.

> Of course we could also think about making an own implementation of the Workspace reader that is more specific to m2e and drop the takari stuff. There is really not much to to for m2e and we already have a view of the workspace projects so the implementation cost would be low.

At the moment I have not yet made myself very familiar with the code so I cannot say much about that. But as long as the information is only used internally inside m2e and not outside, I think it is likely reasonable to use an own specific implementation. Especially since that project is very inactive.

**Comment by laeubi** [comment]
> This change or the major version jump to m2e 2.0.0?

If we adopt code from takari :-) As it already have Some XYZ2

> But as long as the information is only used internally inside m2e and not outside

This is used for the "resolve workspace artifacts" feature when running maven on CLI or embedded.

**Comment by HannesWell** [comment]
> > This change or the major version jump to m2e 2.0.0?
> 
> If we adopt code from takari :-) As it already have Some XYZ2
> 
Sorry, I misunderstood you. Yes totally makes sense! I would even suggest to keep it internal in this case.

> > But as long as the information is only used internally inside m2e and not outside
> 
> This is used for the "resolve workspace artifacts" feature when running maven on CLI or embedded.
So I can use Maven projects in my workspace as build plugins in a Maven build launched from my workspace?
I didn't knew this was possible but its very handy.

**Comment by HannesWell** [comment]
@mickaelistria or @laeubi the workspace.cli itself aside, can you tell if the failure is a caused by a flaw in the signing produce of the `org.eclipse.m2e.workspace.cli.source,0.3.1` bundle or could the build failure be caused be some wrong configuration in the m2e build?

**Comment by HannesWell** [comment]
Looks like the same problem appears for `m2e.workspace.cli` 0.4.0.

**Comment by laeubi** [comment]
The problem might be that the signature is just too old to be verified (e.g. using an outdated algorithm, the certificate has expired, ...). So we yould either include the source as discussed or simply keep it as-is currently.

**Comment by HannesWell** [comment]
> The problem might be that the signature is just too old to be verified (e.g. using an outdated algorithm, the certificate has expired, ...). So we yould either include the source as discussed or simply keep it as-is currently.

I assumed that as well, but then it is the question why it only affects the source jar and not the main jar?

However if we don't find a solution how this can be consumed without furthre changes of the workspace.cli artifacts I suggest to leave it as it is for now and consinder the move from the separate repo for m2e-2.0.

**Comment by HannesWell** [comment]
The changes in `MavenLaunchUtils` are already on the master as part of PR #548.

Since the inclusion of the sources is not working I think we should close this one.
I will open an issue to discuss how to further handle the m2e.workspace.cli.

**Pull request closed without merging**
