### PR TITLE
M2Eclipse gets stuck in endless update loop

### PR DESCRIPTION
**Pull request by laeubi**
Fix https://github.com/eclipse-m2e/m2e-core/issues/123

Lets see if simple things just work...

### CODE REVIEW

**Comment by laeubi** [comment]
@mickaelistria this has solved my endless cycle but two tests complain, can you take a look what these tests are missing or what feature they depend on so I can try to enhance the solution?

**Comment by mickaelistria** [comment]
Those tests are important. I think you can reproduce them manually to get a sense of what are the bad effects of your proposal. Basically, in some cases, some projects really need to be processed multiple times and your code skips that. The condition to skip a refresh needs to be narrower.

**Comment by laeubi** [comment]
> what are the bad effects

Stuck in an endless cycle is (for me) much more bad :-)

> The condition to skip a refresh needs to be narrower.

I'll try a more sophisticated check ... :-\

**Review by mickaelistria — APPROVED** [review]
This seems quite good!

**Comment by laeubi** [comment]
If you think that it don't harm I'd like to merge this, maybe it will need improvements but I can only check for sure next time the build-loop occurs again ...

**Pull request merged**
