### PR TITLE
Add com.google.guava to update site

### PR DESCRIPTION
**Pull request by laeubi**
Fix https://github.com/eclipse-m2e/m2e-core/issues/1520

### CODE REVIEW

**Comment by HannesWell** [comment]
No objections to add new requirements, but this seems not to be present:
```
 [ERROR] Cannot resolve project dependencies:
 [ERROR]   Software being installed: org.eclipse.m2e.repository raw:2.1.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.1.0-SNAPSHOT
 [ERROR]   Missing requirement: org.eclipse.m2e.repository raw:2.1.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.1.0-SNAPSHOT requires 'org.eclipse.equinox.p2.iu; javax.interceptor.api 0.0.0' but it could not be found
```

**Comment by HannesWell** [comment]
Looking at the repo I think more that guava is actually missing from the m2e repo.

**Comment by laeubi** [comment]
I now added `com.google.guava` instead, maybe this already helps...

**Review by HannesWell — APPROVED** [review]

**Comment by HannesWell** [comment]
In an Eclipse Modelling with the latest release I also get:

```
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1692782064346
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: M2Eclipse's archetype-common 3.2.1.1 (org.eclipse.m2e.archetype.common 3.2.1.1) requires 'java.package; org.jdom2 0.0.0' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1692782064346
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.feature.feature.group 2.4.100.20230823-0832
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: M2E - Maven Integration for Eclipse 2.4.100.20230823-0832 (org.eclipse.m2e.feature.feature.group 2.4.100.20230823-0832)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.archetype.common [3.2.1.1,3.2.1.1]
```
So it would probably be good to add `https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-09/` as reference as well.

**Comment by HannesWell** [comment]
> So it would probably be good to add `https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-09/` as reference as well.

I appended those changes on top of yours via the GH UI, could you please squash them together?

**Pull request merged**
