### PR TITLE
[Maven-Runtime] Embed Maven 3.8.5

### PR DESCRIPTION
**Pull request by HannesWell**
This embeds Maven 3.8.5.

At the moment the staged version of the mentioned released is used. As soon the final release is performed this PR has to be updated accordingly.

### CODE REVIEW

**Comment by HannesWell** [comment]
@laeubi, @mickaelistria do you have an idea why the tests fail?
I can reproduce the failure locally and it is definitely due to new Maven version (with the 3.8.4 the tests pass, wit 3.8.5 they fail).
If one of you knows the cause, the question is: Is this a regression that has to be fixed in Maven or in M2E?

**Comment by laeubi** [comment]
Thy seem to be related to the leminnx editorthe error message is a bit unclear, maybe we can enhance it?

**Comment by mickaelistria** [comment]
With a fix on lemminx-maven and #604 to consume it, things should now work better with Maven 3.8.5. Can you please rebase and push --force to update this PR and see whether issues are now fixed?

**Comment by mickaelistria** [comment]
Actually, no need to rebase, the `pr-merge` job has taken care of trying this patch against master and shows it's successful.

**Comment by HannesWell** [comment]
Thanks Mickael. 👍🏽 
Just to be sure I rebased nevertheless.

**Comment by HannesWell** [comment]
> Did you run the IP check against Maven 3.8.5 libraries and its transtive deps to verify there is no issue in term of license or IP?

Sorry I forgot that, but just set it up and run it (your workflow from https://github.com/eclipse-m2e/m2e-core/pull/399#issuecomment-976337189) seems not to work anymore. I assume because of the changed TP resolution in Tycho 2.7.0.
However the dash-tool gives the following results:

```
[INFO] --- license-tool-plugin:0.0.1-SNAPSHOT:license-check (license-check) @ m2e-core ---
[INFO] Querying Eclipse Foundation for license data for 438 items.
[INFO] Found 285 items.
[INFO] Querying ClearlyDefined for license data for 27 items.
[INFO] Found 27 items.
[INFO] License information could not be automatically verified for the following content:
[INFO] 
[INFO] maven/mavencentral/io.takari.m2e.workspace/org.eclipse.m2e.workspace.cli/0.3.1
[INFO] maven/mavencentral/org.apache.maven/maven-artifact/3.8.5
[INFO] maven/mavencentral/org.apache.maven/maven-builder-support/3.8.5
[INFO] maven/mavencentral/org.apache.maven/maven-model-builder/3.8.5
[INFO] maven/mavencentral/org.apache.maven/maven-model/3.8.5
[INFO] maven/mavencentral/org.apache.maven/maven-repository-metadata/3.8.5
[INFO] maven/mavencentral/org.apache.maven/maven-resolver-provider/3.8.5
[INFO] maven/mavencentral/org.apache.maven/maven-settings-builder/3.8.5
[INFO] maven/mavencentral/org.apache.maven/maven-settings/3.8.5
[INFO] 
[INFO] This content is either not correctly mapped by the system, or requires review.
[INFO] 
[INFO] 
[INFO] Summary file was written to: C:\dev\git\eclipse.m2e-core\target\dash\summary
```

Should I revert this change for now and await the IP reviews?
I can set up to query them this evening (or maybe it just happens automatically in the meantime).

**Comment by HannesWell** [comment]
> Let's just wait a bit and retry. ClearlyDefined tends to update its database on request, so if this is the first request, it could be that clearlydefined will have it updated soon. So let's not revert and instead retry later, and if necessary, we'll open IP reviews to Eclipse Foundation IP Team. We just need to make sure we don't forget about it before we release.

OK, good. I will be watching it.

**Comment by mickaelistria** [comment]
Some updates too place but some artifacts requires Eclipse Foundation review
```
$ java -jar /home/mistria/git/dash-licenses/core/target/org.eclipse.dash.licenses-0.0.1-SNAPSHOT.jar maven.deps -project technology.m2e -review -token $GITLAB_TOKEN
[main] INFO Querying Eclipse Foundation for license data for 39 items.
[main] INFO Found 17 items.
[main] INFO Querying ClearlyDefined for license data for 22 items.
[main] INFO Found 22 items.
License information could not be automatically verified for the following content:

maven/mavencentral/org.apache.maven/maven-model-builder/3.8.5
maven/mavencentral/org.apache.maven/maven-resolver-provider/3.8.5

This content is either not correctly mapped by the system, or requires review.


Setting up a review for maven/mavencentral/org.apache.maven/maven-model-builder/3.8.5.
 - Created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2110
Setting up a review for maven/mavencentral/org.apache.maven/maven-resolver-provider/3.8.5.
 - Created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/2111

```

**Comment by HannesWell** [comment]
Thank you Mickael for requesting the review. It looks like it was successful.

When I run the license-check for the entire repo only the license for `org.eclipse.m2e.workspace.cli` is not found, which is EPL and in a sibling repo.
```
[INFO] --- license-tool-plugin:0.0.1-SNAPSHOT:license-check (default-cli) @ m2e-core ---
[INFO] Querying Eclipse Foundation for license data for 438 items.
[INFO] Found 287 items.
[INFO] Querying ClearlyDefined for license data for 25 items.
[INFO] Found 25 items.
[INFO] License information could not be automatically verified for the following content:
[INFO]
[INFO] maven/mavencentral/io.takari.m2e.workspace/org.eclipse.m2e.workspace.cli/0.3.1
[INFO]
[INFO] This content is either not correctly mapped by the system, or requires review.
[INFO]
[INFO]
[INFO] Summary file was written to: C:\dev\git\eclipse.m2e-core\target\dash\summary
[ERROR] Dependency license check failed. Some dependencies need to be vetted.
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
