### PR TITLE
Bug 568385 - allow project to resolve itself

### PR DESCRIPTION
**Pull request by snjeza**
Related test PR: https://github.com/tesla/m2e-core-tests/pull/122

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
@fbricon do you plan to review this one?

**Comment by fbricon** [comment]
I am

**Comment by mickaelistria** [comment]
> I am checking it

@fbricon any news yet?

**Comment by fbricon** [comment]
LGTM Please change the commit message to "Bug 568385 - allow project to resolve itself"

**Comment by snjeza** [comment]
> LGTM Please change the commit message to "Bug 568385 - allow project to resolve itself"

Fixed

**Pull request merged**
