### PR TITLE
Guava 30.1 => Exclude jsr305

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
@tony-- this seems to work, and I've also submitted a fix on Platform side to minimize chances of this issue to occur: https://bugs.eclipse.org/bugs/show_bug.cgi?id=569770

**Comment by tony--** [comment]
Thanks @mickaelistria.  I'd like to clean up my two commits.  The second one was just an experiment to try out adding the dependency to indexer, but I think its not necessary.  

I'll add another commit that removes [this line](https://github.com/eclipse-m2e/m2e-core/pull/61/files#diff-003248e3d189c2c0df82a5d74689f1f66ddb61f6236a183c6817537922dad4e0R125)

**Comment by tony--** [comment]
Hmm, well maybe you need to do that.  I don't think I can push to your repo.

**Comment by mickaelistria** [comment]
Feel free to pick my commit to your local branch PR and to squash it or whatever and to apply any change you think it worth it.

**Comment by mickaelistria** [comment]
Feel free to pick my commit to your local branch PR and to squash it or whatever and to apply any change you think it worth it.

**Comment by mickaelistria** [comment]
Outdated.

**Pull request closed without merging**
