### PR TITLE
Execute Maven plug-ins to generate sources required for M2E compilation

### PR DESCRIPTION
**Pull request by HannesWell**
The connectors for the 'maven-dependency-plugin' and the 'modello-maven-plugin' are currently broken because they are not yet adapted to M2E 2.0. Threrefore command m2e explicitly to execute those goals.

In order to make this work in the IDE the o.e.m2e.core/pom.xml had to be re-created.

@merks this should fix your problem from https://github.com/eclipse-m2e/m2e-core/discussions/1071.
You can try it by deleting the content of the src-gen folder and performing a workspace clean+full build afterwards.

### CODE REVIEW

**Comment by fbricon** [comment]
FYI m2eclipse-modello compatible with m2e 2.x is available from https://github.com/tesla/m2eclipse-modello/releases/download/latest/
The m2e catalog has been updated

**Comment by HannesWell** [comment]
> FYI m2eclipse-modello compatible with m2e 2.x is available from https://github.com/tesla/m2eclipse-modello/releases/download/latest/ The m2e catalog has been updated

Thanks for that hint. This makes most of of this change obsolete. I will revert tomorrow and update the M2Es Oomph setup accordingly.

**Comment by laeubi** [comment]
For me signing do not mean anything ... everyone can buy a signing certificate for a few dollars and the eclipse one is accessible to every eclipse-committer...

**Comment by HannesWell** [comment]
That's all right. But not everybody knows that and has the same attitude in that regard. and therefore I'm a bit concerned that this could scare/annoy new contributors and maybe even existing ones.

**Comment by fbricon** [comment]
eclipse signing is only available to projects built on the EF infra, which doesn't apply to m2eclipse-modello.
Now I can't setup jar signing for Takari projects, nor do I care enough. Maybe @jvanzyl would be interested to do it.

**Comment by HannesWell** [comment]
> eclipse signing is only available to projects built on the EF infra, which doesn't apply to m2eclipse-modello. Now I can't setup jar signing for Takari projects, nor do I care enough. Maybe @jvanzyl would be interested to do it.

That's right. An alternative would be to use PGP signing.
Maybe that's simpler to set up.

**Pull request merged**
