### PR TITLE
[TP] update to Eclipse 4.30 and latest versions of other dependencies

### PR DESCRIPTION
**Pull request by HannesWell**
Create this update for now as a draft to test compatibility with the upcoming release.

### CODE REVIEW

**Comment by HannesWell** [comment]
Looks like the m2e.tests.common need to adapt to the migration from Jetty 10 to 12.
@laeubi or @merks do you know anything about how to do that?

**Comment by merks** [comment]
No, for BIRT and WTP, someone else did the work.  

Maybe these changes will give inspiration:

- https://github.com/eclipse-birt/birt/commit/797343d90b198a27603891eafacf48451c84b612#diff-b8af6fab307d2d5edd31e69ac60b044cf529413185a0b978711b004eb0f46934
- https://github.com/eclipse-birt/birt/commit/fa2d991dbdbf7dc28eadba283f9d433b23659c6e

**Comment by merks** [comment]
I guess you hold off updating guava until this is done?

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12173

**Comment by HannesWell** [comment]
> I guess you hold off updating guava until this is done?
> 
> https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12173

Actually I wanted to include the Guava update, but have to admit that I forgot it. Thanks for the heads up. But with that issue open, I'll postpone this to another PR.

**Comment by laeubi** [comment]
@HannesWell what do you think about replace guava cache with the alternative you mentioned recently?

**Comment by HannesWell** [comment]
> @HannesWell what do you think about replace guava cache with the alternative you mentioned recently?

I would be in favor of that and already did that in https://github.com/eclipse-m2e/m2e-core/pull/507, but it was not fully working and parts of it were reverted in https://github.com/eclipse-m2e/m2e-core/pull/928. But as mentioned there, I assume that with small extra steps it can still be done without Guava.

See also https://github.com/eclipse-m2e/m2e-core/issues/1288.
But in the end the Maven runtime requires Guava and we (as m2e) therefore cannot really get rid of Guava as long as Maven requires it.

**Comment by HannesWell** [comment]
@laeubi do you have any idea why the new bnd version generates he packages javax.lang.model.element, java.lang.annotation, java.lang on Jenkins but only (the old packages) `javax.lang.model.element` on the GH runners in the `OSGiMetadataGenerationTest`?

**Comment by laeubi** [comment]
I just remmber that I adjusted Tycho tests as well to include the new packages, it could be that Tycho is using a cached variant so maybe you need to delete the caches here: 
https://github.com/eclipse-m2e/m2e-core/actions/caches

**Comment by HannesWell** [comment]
OK, thanks for the hint.
I deleted all caches and restarted the builds. Lets see if this helps.

**Comment by HannesWell** [comment]
> I just remmber that I needed to adjusted Tycho tests to include the new packages, it could be that Tycho is using a cached variant so maybe you need to delete the caches here: https://github.com/eclipse-m2e/m2e-core/actions/caches

Looks like that was it. 🎉
So this is finally ready.

**Pull request merged**
