### PR TITLE
Use SPDX identifier for license

### PR DESCRIPTION
**Pull request by Bananeweizen**
Recommended by Maven documentation and Eclipse EMO.

### CODE REVIEW

**Review by HannesWell — APPROVED** [review]
Looks good.
Thank you.
Could you please add links to the recommendations as comment?

**Comment by HannesWell** [comment]
The build fails with the following error, but this change is very likely unrelated:
```
 [INFO] --- tycho-baseline:4.0.3:verify (baseline-check) @ org.eclipse.m2e.model.edit ---
 [INFO] Adding repository https://download.eclipse.org/technology/m2e/releases/latest
 [INFO] Adding repository https://download.eclipse.org/technology/m2e/releases/latest
 [ERROR] ┌──────────────────────────┬──────────────────────────┬──────────────────────────┬─────────────────────────┬─────────────────────────┬─────────────────────────┐
 [ERROR] │Delta                     │Type                      │Name                      │Project Version          │Baseline Version         │Suggested Version        │
 [ERROR] ├──────────────────────────┼──────────────────────────┼──────────────────────────┼─────────────────────────┼─────────────────────────┼─────────────────────────┤
 [ERROR] │MICRO                     │MANIFEST                  │org.eclipse.m2e.model.edit│2.0.300                  │2.0.300                  │2.0.301                  │
 [ERROR] │                          │                          │-2.0.300-SNAPSHOT.jar     │                         │                         │                         │
 [ERROR] ├──────────────────────────┼──────────────────────────┼──────────────────────────┴─────────────────────────┴─────────────────────────┴─────────────────────────┤
 [ERROR] │..CHANGED                 │HEADER                    │Bundle-License                                                                                          │
 [ERROR] └──────────────────────────┴──────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

I also noticed that the master build is failing since we upgraded to Tycho 4.0.3 while validation the m2e-repository:
https://ci.eclipse.org/m2e/job/m2e/job/master/
@laeubi is this something know?

**Comment by mickaelistria** [comment]
I think the failure here is related: the Bundle-License header is added by BND according to the license described in the pom file. If license changes in pom file, then the bundle changes and thus may need a version bump if there were no other change since last release.

**Comment by laeubi** [comment]
I'm not sure if it is BND or Tycho (some items are read at Tycho level as well) so this seems valid.

But I would have exspected from the output to show the old and the new value (waht would have made this more clear to the user), so it would be good to create a Tycho issue or even a testcase for this.

**Comment by Bananeweizen** [comment]
Related references:
* https://maven.apache.org/pom.html#Licenses
* https://gitlab.eclipse.org/eclipsefdn/emo-team/sbom/-/blob/main/docs/sbom.adoc#sbom-maven

(As I mentioned in an earlier issue, I see such baseline verification errors since months locally when building Tycho)

**Comment by laeubi** [comment]
> As I mentioned in an earlier issue, I see such baseline verification errors since months locally when building m2e

If you think there is a bug/problem please report it (at best with a reproucing testcase) so it could be fixed.

**Comment by mickaelistria** [comment]
The failure here was related. It has caused build to fail constantly for 2 weeks.
Proper solution seems to be version bump of all modified bundles.

**Comment by Bananeweizen** [comment]
thanks @mickaelistria for changing all the bundles now. I wasn't aware this single POM change could have such consequences. Will take note for future changes.

**Pull request merged**
