### PR TITLE
Embed and use Maven 3.8.1 (#159)

### PR DESCRIPTION
**Pull request by vrubezhny**
Fixes: #159
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by akurtakov** [comment]
There is one extra test failure with this patch org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest.testMissingSchemaMarker

**Comment by vrubezhny** [comment]
> There is one extra test failure with this patch org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest.testMissingSchemaMarker

On a clean build of master branch locally I have exactly the same test failure.
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.055 s <<< FAILURE! - in org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest
testMissingSchemaMarker(org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest)  Time elapsed: 1.054 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest.testMissingSchemaMarker(MissingSchemaMarkerTest.java:24)
```

**Comment by vrubezhny** [comment]
> There is one extra test failure with this patch org.eclipse.m2e.editor.xml.MissingSchemaMarkerTest.testMissingSchemaMarker

The following PR should fix the problem: https://github.com/tesla/m2e-core-tests/pull/127

**Comment by mickaelistria** [comment]
I don't think the issue is in the test. It could be that Maven 3.8.1 behaves differently regarding absence of schema.

**Comment by vrubezhny** [comment]
> I don't think the issue is in the test. It could be that Maven 3.8.1 behaves differently regarding absence of schema.

I'm sure the test failure is not related to upgrading to Maven 3.9.1. the test fails because its running order is changed for some reason. There are several test projects with the same groupID/artifactID, so after the MissingSchemaMarkerTest started to be executed after the other test which test project has the same groupID/artifactID,  when testing for the `xsi:schemaLocation` attribute presence a wrong structure document has being used (the one actually came from the previous test) and the `xsi:schemaLocation` attribute exist on that wrong document .
Changing the groupID/artifactID of the test project, giving a unique name to the test project fixes the test issue.

**Comment by mickaelistria** [comment]
Merged, thanks!

**Pull request merged**
