### PR TITLE
Update tycho to 4.0.8

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by HannesWell** [comment]
All these test-failures happen also in the attempt to update to Tycho 4.0.6: https://github.com/eclipse-m2e/m2e-core/pull/1688

I haven't investigated it yet, maybe @laeubi can tell?

**Comment by laeubi** [comment]
From the buildfailure it is a problem due to classfile changes (ECJ update?)

**Comment by HannesWell** [comment]
> From the buildfailure it is a problem due to classfile changes (ECJ update?)

The update to Tycho 4.0.6 already failed in #1688 and IIRC the comparator errors were not the problem and the fixed ECJ version was removed in an attempt to resolve that failure, but it seems like it didn't fix it.
But lets fix the comparator errors first.

**Comment by HannesWell** [comment]
> From the buildfailure it is a problem due to classfile changes (ECJ update?)

The comparator errors are resolved and now we (again) have the 500 test-failures.

**Comment by laeubi** [comment]
As they all fail the same way maybe some change in P2 causing this, I would try to add a direct dependency in the test plugin to make sure its not caused by some indirect dependency missing now.

**Comment by HannesWell** [comment]
> As they all fail the same way maybe some change in P2 causing this, I would try to add a direct dependency in the test plugin to make sure its not caused by some indirect dependency missing now.

The plugin `org.eclipse.m2e.tests` already requires the bundle `org.eclipse.m2e.maven.runtime`.

**Comment by HannesWell** [comment]
> > > As they all fail the same way maybe some change in P2 causing this, I would try to add a direct dependency in the test plugin to make sure its not caused by some indirect dependency missing now.
> > 
> > 
> > The plugin `org.eclipse.m2e.tests` already requires the bundle `org.eclipse.m2e.maven.runtime`.
> 
> The error says that the bundle `org.eclipse.m2e.tests.common` can not find the class...

Right (I just read the first line and checked the test class). But even `org.eclipse.m2e.tests.common` already requires `org.eclipse.m2e.maven.runtime`.

**Comment by laeubi** [comment]
Interestingly I get these errors locally as well with Tycho 4.0.4

**Comment by laeubi** [comment]
As I can "reproduce" it [here](https://github.com/eclipse-m2e/m2e-core/pull/1770) with Tycho 4.0.4 I suspect it must be some kind of classpath ordering problem, e.g that for consistency we order the dependencies differently (either Tycho or P2)...

**Comment by HannesWell** [comment]
With Tycho 4.0.9 we could finally update: https://github.com/eclipse-m2e/m2e-core/pull/1837

**Pull request closed without merging**
