### PR TITLE
Clean up and simplify logback projects

### PR DESCRIPTION
**Pull request by HannesWell**
An attempt to clean up and simplify the `logback.appender` and `logback.configuration` plug-ins.

In order to direct the attention to the relevant parts of the logic utility code was extracted into own methods, but not re-used utility classes mere merged.

Furthermore added comments (with references to bug-reports) to locations that seem to be unnecessarily cumbersome at the first look, but turned out to be relevant in the end.
And some other minor improvements (e.g. avoid `File.toURL()`).

### CODE REVIEW

**Comment by HannesWell** [comment]
@mickaelistria what do you think about this change?

Especially for the `MavenConsoleAppenderImpl` and `LogPlugin.start()` (how configureLogback() is called) I actually expected more simplifications in the beginning, because it seemed to be cumbersome.
But while working on it and testing the changes I noticed that it was necessary. Therefore I tried to extract the complicated parts so that they disturb the actual logic less and added comments/explanations where things have to be as they are, so that others don't waste their time like I did attempting to simplify it.

**Comment by HannesWell** [comment]
The build fails while assembling the m2e site:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.m2e.site 1.16.0.qualifier
[ERROR]   Missing requirement: org.eclipse.m2e.sdk.feature.feature.group 1.18.2.20210928-1606 requires 'org.eclipse.equinox.p2.iu; org.eclipse.m2e.logback.configuration.source [1.16.3.20210909-2052,1.16.3.20210909-2052]' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.m2e.site 1.16.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.m2e.sdk.feature.feature.group 0.0.0
```

**Comment by HannesWell** [comment]
Build is now successful and has only the usual failures.

Unless nobody else has objections I will merge this PR in the next days.

**Comment by mickaelistria** [comment]
Feel free to rebase and merge at your own convenience.

**Comment by HannesWell** [comment]
Squashed-and-merged it.

I think it is a good workflow for changes that are small enough to be one commit: Start the PR with a single commit, push follow up changes that are required from the review process or due to test-failures and squash and merge it in the end. This way no force push is necessary so the changes in the review-process are still traceable but in the in end we still get a clean history with only one commit.

**Comment by mickaelistria** [comment]
Last build has the console output test failing: https://ci.eclipse.org/m2e/job/m2e/job/master/86/testReport/junit/org.eclipse.m2e.core.ui.tests/ConsoleTest/testConsoleHasOutput/ . I've retriggered the build, if the issue persists, we'll have to revert.

**Comment by mickaelistria** [comment]
OK, it seems fine with next build, so nothing to worry particularly about this patch.

**Comment by HannesWell** [comment]
> Last build has the console output test failing: https://ci.eclipse.org/m2e/job/m2e/job/master/86/testReport/junit/org.eclipse.m2e.core.ui.tests/ConsoleTest/testConsoleHasOutput/ . I've retriggered the build, if the issue persists, we'll have to revert.

That's an interesting view. Until now I was searching the console for error markers, but this one is much more convenient.

Thanks for starting another build.

**Pull request merged**
