### PR TITLE
Clean-up and simplify MavenImpl

### PR DESCRIPTION
**Pull request by HannesWell**
Before we remove the deprecated methods, `MavenImpl` can be cleaned-up.

I can then take care of removing the deprecated methods.

### CODE REVIEW

**Comment by laeubi** [comment]
As we are talking about cleanup:

I noticed there are some (inconsistent) formatting and code templates enabled on the project level.
I wonder if we can agree to remove all thos project level source config and simply use "Eclipse" Formatting profile in all cases?

**Comment by HannesWell** [comment]
> I noticed there are some (inconsistent) formatting and code templates enabled on the project level. I wonder if we can agree to remove all thos project level source config and simply use "Eclipse" Formatting profile in all cases?

Yes, I fully support that! I noticed that as well in the past but did not yet have the time to bring this up.

**Comment by akurtakov** [comment]
> > I noticed there are some (inconsistent) formatting and code templates enabled on the project level. I wonder if we can agree to remove all thos project level source config and simply use "Eclipse" Formatting profile in all cases?
> 
> Yes, I fully support that! I noticed that as well in the past but did not yet have the time to bring this up.

Fully agree on using "Eclipse" formatting profile. But let's keep the project level source config files saying that, otherwise contributors that have changed their workspace formatting profile to smth else will submit different formatting.

**Comment by laeubi** [comment]
> . But let's keep the project level source config files saying that

I think we can better configure that at the SDK setup I think, these "project settings" tend to diverge as new items are added or defaults are changed.

**Pull request merged**
