### PR TITLE
Remove pom for repository

### PR DESCRIPTION
**Pull request by mickaelistria**
More importantly, remove the extra signing step that was erroneously modifying external bundles; and uselessly signing bundles that are built in the same reactor, but which are already jarsigned as part of their own build.

### CODE REVIEW

**Comment by mickaelistria** [comment]
I think this `eclipse-sign` profile on the repo was the root of many evils...

**Review by HannesWell — APPROVED** [review]
Yes that looks good 👍🏽 
And answers my question in https://github.com/eclipse-m2e/m2e-core/pull/961#issuecomment-1264495489 (with no, not true anymore).

**Comment by laeubi** [comment]
> More importantly, remove the extra signing step that was erroneously modifying external bundles; 

Just wanted to note, that his was not **erroneously** but **required** for a long time by EF that we sign **all content** contributed to simrel, at that time this was mostly the BND-lib, but as of today it is no longer required ...

**Comment by HannesWell** [comment]
> > More importantly, remove the extra signing step that was erroneously modifying external bundles;
> 
> Just wanted to note, that his was not **erroneously** but **required** for a long time by EF that we sign **all content** contributed to simrel, at that time this was mostly the BND-lib, but as of today it is no longer required ...

That's right, https://github.com/eclipse-m2e/m2e-core/pull/520#issuecomment-1020872217 has changed since then.

Lets merge now this not further spread the signed slf4j/logback etc.
Thank you @mickaelistria.

**Comment by mickaelistria** [comment]
An optional next step would be to enable PGP signatures for external artifacts; but as SimRel is likely to re-sign those artifacts with another PGP signatures, I'm not certain it's required. We'll see whether signing 3rd-party artifacts is a requirement for SimRel.

**Comment by laeubi** [comment]
@mickaelistria as far as I know @merks has added a check for the simrel content to be PGP signed, so I assume simrel itself will not do any signing at all.

**Comment by merks** [comment]
Indeed, SimRel does not do signing of any sort.  The aggregator preserves the PGP signature of the contributed repository.

**Comment by merks** [comment]
I see there is no PGP signature in https://download.eclipse.org/technology/m2e/snapshots/2.1.0/ here:

image

And it's not jar signed either.

The missing PGP signature needs to be fixed if you are going to contribute repositories like this to SimRel.

**Comment by HannesWell** [comment]
> The missing PGP signature needs to be fixed if you are going to contribute repositories like this to SimRel.

Sorry for the (simply) question, but how can we set this up for the m2e build?
I assume that just running the `https://maven.apache.org/plugins/maven-gpg-plugin/sign-mojo.html` is not sufficient (especially since it signs the artifacts that are build in the reactor).
How can we tell Tycho/P2 to add PGP signatures? And which key should we add? The original one from Maven-Central, a M2E or Eclipse specific one?
I know these questions have already been discussed in the past, but since many things have changed I'm not certain anymore what is necessary now and how to achieve it.

As a reference I checked the [2022-09 SimRel repo](https://download.eclipse.org/releases/2022-09/202209141001/) and found for `com.google.guava-31.1.0.jre`, so I assume that the non jar-signed deps of m2e also should have the `pgp` properties?
```
    <artifact classifier='osgi.bundle' id='com.google.guava' version='31.1.0.jre'>
      <properties size='12'>
        <property name='maven-groupId' value='com.google.guava'/>
        <property name='maven-artifactId' value='guava'/>
        <property name='maven-version' value='31.1-jre'/>
        <property name='maven-repository' value='eclipse.maven.central.mirror'/>
        <property name='maven-type' value='jar'/>
        <property name='download.size' value='2959479'/>
        <property name='artifact.size' value='2959479'/>
        <property name='download.md5' value='e37782d974104aa3b0a7bee9927c8042'/>
        <property name='download.checksum.md5' value='e37782d974104aa3b0a7bee9927c8042'/>
        <property name='download.checksum.sha-256' value='a42edc9cab792e39fe39bb94f3fca655ed157ff87a8af78e1d6ba5b07c4a00ab'/>
        <property name='pgp.signatures' value='-----BEGIN PGP SIGNATURE-----&#10;&#10;iQIzBAABCAAdFiEEHqdRPin06Yc3+ETKmQpRd/cMpFYFAmMPfFsACgkQmQpRd/cM&#10;pFZHuA/7Bo79N+g5afxeDE1ndZHk6huYr6yqu/fKLAuNj1NkCwnDLy+OTBedgiNU&#10;iRztnjsHJFWNiYPKghVi75tmAQzZ0Rk47LN+da9q2cAxdf8oedW7cCSlaFjdQHHu&#10;c4l002U067NOAqb6U+NL0cMc8nYvpJvgjYI4qD1PWb5jHsYksL8Um68G3R3D3wpV&#10;u67PKncUBQb5lxayx0uEVYw8PXgooM0oyTwTYU5g9Lg3QdtP7ynCSMzkyczKMyYK&#10;pztEHPazDdn7QUnFkNGEdR1IkRyytmonOBlM4V4p9p5AWDpnqd5yi8UPg1xeZM7O&#10;/lSeigFpMUXS6acswy8yHtJdJIP+dbsCJEYnoDOVLxFfIJObTUoUS4KAaX1pxCyO&#10;LYl6gPBwBCRh0Q4tkt92rNwPtX/oDU+68OVPCFPffOvzgjxEvlbpmNgYJ7mueYkn&#10;zt3RGPiLHSUS2yWdnoe0+U1iqO7eWFOmJ9fXJ2Xb6hZon4j3wlAUBE0ppVIe48Gg&#10;DJY1l0I/I/PfxbaJo1Cv4W0udKShXvILoVrbqw6awu69w1lntC8O9DG4QEygZwrk&#10;4cDUYF9hzWZ67XepwwXBsEbsjhqfsiux7G6pfQ2b4xLpJOgm4lcz1jwCDXLOdVlJ&#10;hPTbAWwn7ywkYdnNjAL4mU/XeBSb+WSIxovkEGLro1mPZBk6hbY=&#10;=c3ZH&#10;-----END PGP SIGNATURE-----'/>
        <property name='pgp.publicKeys' value='-----BEGIN PGP PUBLIC KEY BLOCK-----&#10;&#10;mQINBGLNWKoBEAC+JsmdbutiUbLX0jaUd1EBs5PH743yCgo+QP1ZDgBb0k/vzaDr&#10;OzqcmK+DMvkTnnqX9ZlTr2Hr3KK3dDrOSCWVmpq/Eg4L47D8WkcLbn74EtSkb85Z&#10;B4fRub9A3lfd4L9p6uf4ug8A43EID4rwYBaURaiHGZP0L+ZFjl6senlXlb6diPry&#10;0pT5zHtfLFcEElN+VsBxefFz0HkICjz1BkUcFgmILe20RNsej+QauMgD1L4TlU9a&#10;cdhDtoIQKoMaThkYLAPbLeZD0ZksI3YOTla0TzoDLgvP9gthFYFwbzS9lhTeBaVK&#10;C7EhugEzHTNO613VZdjNnulvmhACG6QB+vRUWWLd1JQq128hsqe7zFUimfPs73TC&#10;nYONiyVd0ogLBo9IAjyslw9i+ickPeRnmG7zdvJdUL7HVfMsKkZAkSSqge43s4YW&#10;pp9kgmqjXuqjPEUAQS1JTZ5NA5j4yiH/uVEnfevMBv1v9I1DM8y4mog1kJZsPURh&#10;3IIwctqoclMK4pKTKZoQgMHS9bVoZdKnHoS2rEUgw1AOo+ncgYtFGkZvVYdT7vUj&#10;Hk8Y5PUmW6kNUix9bTCXGGjGlykD42d3dAliamCy82yumwPltCw9lIcrn7w0lPpk&#10;byMsbopIeWUud3jg9ox0dhDICZE2kDYy84dpY/KV7ZyC3Wb6L8sn5iDNewARAQAB&#10;tD1FY2xpcHNlIFdpbmRvd0J1aWxkZXIgUHJvamVjdCA8d2luZG93YnVpbGRlci1k&#10;ZXZAZWNsaXBzZS5vcmc+iQJUBBMBCAA+FiEEhiR1WWnVEFD/SjQTfsRI2HT/RvQF&#10;AmLNWKoCGy8FCQlmAYAFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AACgkQfsRI2HT/&#10;RvRt6g/9G8E8kLh5E+C34lTl4w9G1gW6IkHYI33pM8dRBTu2VwgxpWycdLQtPks7&#10;uUbAdVvG8nqMbENr7l8LljoN5n4I67VNQUeYgXrZjMhw8OUE+HFaPDbZpkHZRIeD&#10;n6TYcLiGAYW4AcgMr0YIoyDpDV+eOrE9UtTp/hFZ9QQioaeaHCIUgHVb564UMibq&#10;ell0ee3LmThm4aTCKAbUhHSU1A75/tac4EaqsgJbNEr1MNuI/sWXE7Mj7PskBMQC&#10;6+FOqYEmf43sk2eEefGX0zrzOe5PUb9445s2Db3n3kToERms717e/h9NzhhrIOLc&#10;oZEJ5i+1+Ss3UEcwWH0/Tm9IMxNPfFSbXKvjXziGRTZM28vd5IFHx4Edgl98dXvS&#10;ResvvgVIHEmRLQGNyO/GyORNZpFniqCAj5Sv1pR570HpKY70UXE+22VE4ceYDJoh&#10;McdBltWRVUgDhe6X39II/J5zqKnQGJgvlQmyEZSSNa0TTadmH36SKdtGqzypaNmw&#10;7OvwXH+RuGATvx4x7/gqVHH9l+XdvVjyE6cfbE3+qfx6jtguDgCM5eSPfdrXXrnr&#10;7e/n38pQtBURMmF0t3pqAiojSYD2gu4gOQaQUsD778z6C2aufTUGjB5I4YmTKb2J&#10;8RUMNVQZH5YN4eeoUJxIhyE7F9qmi/RhFN9AYk9QiHSLP7El8Fq5Ag0EYs1YtwEQ&#10;AKc4ZQF0yaVaqoZTqpkZkd5Su2xswoz2XV5mQkChwJcHQdB1hz7pOaXVGqVbwcRz&#10;MzZCSQJ5+1qbdrL3pI3quszgBDRgHBAL6eXLDaECJjB2PJvFjMGpuX6qLM3YTzpV&#10;nCLusQ3LMqItAu9ERDTHz+Uay4JqKuLRyhk0FKknoRQtqimbithHtto+rUkZagij&#10;aIMgddRf6buKVMmI5v9H/KuBFnJMnNh7vLcA3+vJ96o0eGjuz1sujjq1OXl0zFaT&#10;oqLjb3fSyeWMhhCxdCu9sWtk103pKt5cDtOknvILQNSijjLh9TG4Iv5vKvbKywNP&#10;NJcxpLscavL47igBJ0ITrh1WK75Iiqh4oMXJGCaH6NEJBN1wVHDpVhDDeIpqVPPK&#10;G+sJqcBZ45dAEL/nfmosCB5YzEbSDSETP/mjLS6WQ/Wy/+/xdHWMk8krJ0GtcpMI&#10;hkItXzfgbU8I6eU5Ycc55L1jl2yPipoK701V5NzYwkgF+vbU4Cr5JAa0E+N/FmxF&#10;IVnUh6M4ts6Nw2JbrtMjkYeuEgW56lrbe3npkAfoICnuXsXrB0uinRS7zbvw/GPv&#10;8lgddL0fGtH5rIV6ysjqoLl4d2VH9UFKx5djJ1Pj9VAkXFIiNHNnCcHyNZdrj+LD&#10;vhoOlRKvWOYiqS1ugHgcLMIgXTuE2Xta9iBesExoSK5bABEBAAGJBHIEGAEIACYW&#10;IQSGJHVZadUQUP9KNBN+xEjYdP9G9AUCYs1YtwIbAgUJCWYBgAJACRB+xEjYdP9G&#10;9MF0IAQZAQgAHRYhBB6nUT4p9OmHN/hEypkKUXf3DKRWBQJizVi3AAoJEJkKUXf3&#10;DKRW3VQP/izxWYrOhp251QGiwKlrfjwZXMeQzuZet/D4Zxlch0IV2HTS5elYZpLW&#10;56mk4Qa5mgBPNqeCqZBnS6ztSP+oto6/XBNsiRWUkJpiSLcwF7o7C6v/eeuWR/i8&#10;Q1a/zYKUrvkfg7THd6kzyqT0REYgM70zktgjka0HJHIwRQfyE3gL3SCVFTxy0o8b&#10;5lz7WMFR6m45NpnJqnBGwXSFw0jSwo/mL7OJ9cYxDp1C/3KLevtfw8jfU0ogEY+X&#10;QYEDKOIA6O300/XfNir0uqMriXQfCzOdPHxw/o9msKD1Pl5Zsx91JzEBVri6MClr&#10;SSaeBB7DYShd6z6qC3Yoh4PguzJQJspeBmyxP7OBFHwTusetkaVU3UWobYbl3HBu&#10;EruABM7pqfm17xCdYt2sQHmvQaiOnNm7z8oSesI1h+6rNNx1o+HEkaf6NZ+ynjvr&#10;Bbvb0WmfQR5EzC/YtlvnKRLyI4GsxHvXQWFF7zEvs4hxR0qcRuB041Xmj1X9Puj3&#10;jsX8SVEYGnqrgEC3V06I4peYiD4UuSWUuj8kHqEVv+eMrI+h0L9zUoaFzEtsHQ8Z&#10;ambK10XwH2gxXDRSS6UDBD8ipNO7Rcwoz0Hds17m5MRs0r5s6kDaPnzR4/d7WQhz&#10;iiPNuD7QO8Jp9Ttm3fbmr4Qgo2CwtDcBTHt/DIfEHoTJsHwJkSzdL4gP/A8NJea5&#10;qAutr5NlnR5tBqa/tgmW6liRS8DOooCfCAGhgWXtL88xcgG9keLWkF5p4jZj3u21&#10;r2d/ghddnzmTwrjmz0ODW5LbXbdgna3PTE4QHskQnEJ7fQNHsP9uU4CADlFNBcw4&#10;cMV5G6LYr4YAxoTT2pxysIMJqZvZ9/GALeY7dBiIBnG9uFHWoqgdcux2IBfpZ7UT&#10;JgKUc7BRkJbIwZWiPVM71zFvOQJFvEtLnem74lmW+ipCj+hwQxGgCbF/AyvyvqN0&#10;5aqysDSAmlXwjvek3fuVemnjiZwy0TgYl0tXvLZbwCd2GJUgpWNI/dHaQaV0ZdQM&#10;f40cjymE1N5QCAayuNToMmIP5jUvrZSkaurB2wiMOM+tzf+OYCp/Mq5PY46WSczu&#10;OFdKwia9VYRP8u9QKr8Yz17LhGxC9LrzKtUuJoZ5eiUzVXeU+i6uLzZz1ZzoweZV&#10;5qRG5OBB4NXY32peoWr/kXBU29X3LmHWUw1uqe+N9j/3s0FjtOM8oXR254FtWF9h&#10;NFjhjfKFaMuwIS51jf6qR9Ygqbs7Z9h8tgkTqXg1IGgDtcJKcT1aJvyDOXmjW/+b&#10;UFEkj3BAv41hkawxCpTwAKbAwVQLw9Y0TqTNsWH+8IgdGR+OeEou6j8Grw2TV974&#10;5D0/rIoMUHlOPyk/bz9ZrZp5qlBt7M9l7BBP&#10;=ZVEV&#10;-----END PGP PUBLIC KEY BLOCK-----'/>
      </properties>
    </artifact>
```

**Comment by laeubi** [comment]
The only think I know is https://docs.google.com/document/d/1MnDBvOUwKvKacB-QKnH_PzK88dUlHkjs-D-DWEKmvkY/edit but @merks  or @mickaelistria might be able to give some more focused guidance.

**Comment by HannesWell** [comment]
> The only think I know is https://docs.google.com/document/d/1MnDBvOUwKvKacB-QKnH_PzK88dUlHkjs-D-DWEKmvkY/edit but @merks or @mickaelistria might be able to give some more focused guidance.

Looks doable. Only the gpg setup looks like a little magic for people that use linux shell scripts only occasionally and the only simple ones:
https://github.com/eclipse/tm4e/blob/master/Jenkinsfile#L14..L19

**Comment by merks** [comment]
@HannesWell I'll get back to you tomorrow with some details of what needs to be done, unless @mickaelistria provides the details in the meantime...

**Comment by mickaelistria** [comment]
OK, I got confused and thought SimRel was re-signing.
So we'll need to run PGP signing. Basically we should reintroduce the profile from the repository pom and replace the jarsigner by Tycho PGP signing (once m2e's Jenkins is properly setup). The linked document is the best doc I'm aware of, and I see you found other examples like TM4E already.
That is AFAIK the current best approach; however it was discussed a few times with @laeubi that the best time when to add those signatures to external artifacts would be when generating the target-platform internally in Tycho. I don't remember if it was already enabled though.

**Comment by laeubi** [comment]
> That is AFAIK the current best approach; however it was discussed a few times with @laeubi that the best time when to add those signatures to external artifacts would be when generating the target-platform internally in Tycho. I don't remember if it was already enabled though.

Maybe you mean 
- https://github.com/eclipse-tycho/tycho/issues/661

that would then reuse the (original) signature from maven.

**Comment by mickaelistria** [comment]
A mix of this issue and another one I guess; as reusing Maven signatures is not desired; however adding signatures very early in p2 metadata generation instead of later in repository aggregation is indeed a good thing.
But I read that it's not available yet, so using pgp signer on the p2 repo seems to be the current best solution.

**Comment by laeubi** [comment]
At least I don't plan anything in that area because it would complicate things a lot and there is actually no value for the build, the signature is just relevant for a repository (or maybe a product) and there I personally would desire the original signature more than any newly generated one that again deviates from the idea of reusing existing (meta) data from maven central.

**Pull request merged**
