### PR TITLE
Run GH-workflow on Linux, Windows and Mac

### PR DESCRIPTION
**Pull request by HannesWell**
Lets see if the build passes on Windows as well.

Fixes https://github.com/eclipse-m2e/m2e-core/issues/1080.

### CODE REVIEW

**Comment by HannesWell** [comment]
> @HannesWell the `name: test-results` should contain the so one run do not overwrite the results of the other.

Thanks. Fixed it.

**Comment by HannesWell** [comment]
The Test result upload for the Windows build still fails with:
`Error: ENOENT: no such file or directory, realpath 'D:\a\m2e-core\m2e-core\products\m2e-ide\target\products\m2e-ide\macosx\cocoa\aarch64\Eclipse.app\Contents\Eclipse\features\org.eclipse.ecf.filetransfer.httpclient5.feature.source_1.1.600.v20220215-0126\META-INF\maven\org.eclipse.ecf\org.eclipse.ecf.filetransfer.httpclient5.feature'`

I don't understand that. Anybody has a hint?
The Mac build has test-failures as anticipated.

**Comment by laeubi** [comment]
Sadly there is a bug in the upload workflow see for example:
- https://github.com/eclipse-platform/eclipse.platform/issues/278

**Comment by laeubi** [comment]
@HannesWell do you like to finish this?

**Comment by HannesWell** [comment]
@kwin you mentioned in https://github.com/actions/upload-artifact/issues/240#issuecomment-1346982359 that with a recent node.js the windows issues should be fixed. Can you explain what has to be changed in this repo to get a fixed version?

If we don't make it work on windows and #1154 at least we can alread merge this for Linux and Mac only and add Windows later, when it is working.

But the current failure on Windows seem to be a baseline issue.

**Comment by kwin** [comment]
> @kwin you mentioned in [actions/upload-artifact#240 (comment)](https://github.com/actions/upload-artifact/issues/240#issuecomment-1346982359) that with a recent node.js the windows issues should be fixed. Can you explain what has to be changed in this repo to get a fixed version?

Nothing, it should just work if GitHub Runners are connected to this repo and not custom ones.

> But the current failure on Windows seem to be a baseline issue.

Indeed not related to the NodeJS issues related to long paths on Windows.

**Comment by HannesWell** [comment]
> > @kwin you mentioned in [actions/upload-artifact#240 (comment)](https://github.com/actions/upload-artifact/issues/240#issuecomment-1346982359) that with a recent node.js the windows issues should be fixed. Can you explain what has to be changed in this repo to get a fixed version?
> 
> Nothing, it should just work if GitHub Runners are connected to this repo and not custom ones.

We use the GH-runners so that should work already.
> 
> > But the current failure on Windows seem to be a baseline issue.
> 
> Indeed not related to the NodeJS issues related to long paths on Windows.

How did you identify the long paths as an issue? From my local builds I only know that there are baseline issues because on Windows text files are usually checked out with windows-style lineendings why they are committed in git and in the p2 base-line repo with linuy-style lineendings. 
I already started https://github.com/eclipse-tycho/tycho/pull/1891 for that but didn't have the time to continue.

**Comment by kwin** [comment]
I didn’t but @laeubi did in https://github.com/eclipse-m2e/m2e-core/pull/1081#issuecomment-1326033979

**Comment by kwin** [comment]
Maybe we can disable Windows until the baseline issues are resolved (or just disable baselining for the time being on Windows with a specific Maven profile)

**Comment by HannesWell** [comment]
> I didn’t but @laeubi did in [#1081 (comment)](https://github.com/eclipse-m2e/m2e-core/pull/1081#issuecomment-1326033979)

Ah, sorry I misunderstood your comment. Just disregard mine.

**Comment by HannesWell** [comment]
> Maybe we can disable Windows until the baseline issues are resolved (or just disable baselining for the time being on Windows with a specific Maven profile)

Yes, I thought about that as well. Disabling it temporarily in a profile on windows (or at least downgrade it to warnings) seems reasonable in that case. I'll try that tomorrow.

**Comment by HannesWell** [comment]
Now we have again the initial error...
`Error: ENOENT: no such file or directory, realpath 'D:\a\m2e-core\m2e-core\products\m2e-ide\target\products\m2e-ide\macosx\cocoa\aarch64\Eclipse.app\Contents\Eclipse\features\org.eclipse.ecf.filetransfer.httpclient5.feature.source_1.1.701.v20221112-0806\META-INF\maven\org.eclipse.ecf\org.eclipse.ecf.filetransfer.httpclient5.feature'`

**Comment by HannesWell** [comment]
On Linux and Mac this passes now. So lets enable that for now and add Windows later, when it is working.

**Pull request merged**
