### PR TITLE
[Runtime] Embed Maven 3.8.3

### PR DESCRIPTION
**Pull request by HannesWell**
Second attempt to embed Maven 3.8.2 after PR #323.

As reported in issue #324 there were test-failure on the master branch, that are also expected now and have to be solved first.

### CODE REVIEW

**Comment by mickaelistria** [comment]
OK. so we see the expected test failure. Good! No let's just find a cause and a solution for it...

**Comment by HannesWell** [comment]
Yep. I can investigate it.
But IMHO this should not be merged before https://github.com/eclipse/tycho/issues/261 is fixed, because otherwise you cannot build m2e with itself from the IDE and I suspect that it is the same for other Eclipse projects that use the P2Metadata goal.

**Comment by mickaelistria** [comment]
A vote has started on the mailing-list and a Maven 3.8.3 release is going to happen soon.

**Comment by HannesWell** [comment]
> 
> 
> A vote has started on the mailing-list and a Maven 3.8.3 release is going to happen soon.

Thanks for the hint! Do you mean this mail?:
https://lists.apache.org/thread.html/rec607477d7053e59e02825bafe2e13539bc8bd4484eee024cd9b6967%40%3Cdev.maven.apache.org%3E

I embedded the staged Maven 3.8.3 locally and the tests seem to pass now (except for the usual failure). Let's see if this also works on Jenkins.

**Comment by HannesWell** [comment]
Build has just the usual build failure, so it looks like we are lucky and the problem (whatever it was) is solved with the new Maven version and we only have to wait for the official release.

**Comment by mickaelistria** [comment]
Maven 3.8.3 was released today; you may update and un-draft this PR.

**Comment by mickaelistria** [comment]
replaced with #343

**Comment by HannesWell** [comment]
> 
> 
> replaced with #343

Thanks Mickael for taking care of it.

**Pull request closed without merging**
