### PR TITLE
fix mac profile

### LINKED ISSUE #1046: You requested to install 'osgi.bundle; org.eclipse.jdt.launching.macosx 0.0.0' but it could not be found
When trying to execute `mvn clean verify` I get the following error on module `org.eclipse.m2e.tests.common`

```
...
[DEBUG] -- end configuration --
[DEBUG] Class org.eclipse.m2e.tests.common.AbstractLifecycleMappingTest matches the current filter.
[DEBUG] Class org.eclipse.m2e.tests.common.AbstractLifecycleMappingTest matches the current filter.
[DEBUG] No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from tycho-extra-1667843090263 0.0.0.1667843090263 to osgi.bundle; org.eclipse.jdt.launching.macosx 0.0.0.; Unable to satisfy dependency from tycho-1667843090269 0.0.0.1667843090269 to osgi.bundle; org.eclipse.jdt.launching.macosx 0.0.0.; No solution found because the problem is unsatisfiable.]
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install 'osgi.bundle; org.eclipse.jdt.launching.macosx 0.0.0' but it could not be found
[ERROR]
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.240 s
[INFO] Finished at: 2022-11-07T18:44:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:3.0.0:integration-test (default-integration-test) on project org.eclipse.m2e.tests.common: Execution default-integration-test of goal org.eclipse.tycho:tycho-surefire-plugin:3.0.0:integration-test failed: Cannot resolve dependencies of MavenProject: org.eclipse.m2e:org.eclipse.m2e.tests.common:2.0.2-SNAPSHOT @ /Users/konradwindszus/git/eclipse/m2e-core/org.eclipse.m2e.tests.common/.tycho-consumer-pom.xml: See log for details -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:3.0.0:integration-test (default-integration-test) on project org.eclipse.m2e.tests.common: Execution default-integration-test of goal org.eclipse.tycho:tycho-surefire-plugin:3.0.0:integration-test failed: Cannot resolve dependencies of MavenProject: org.eclipse.m2e:org.eclipse.m2e.tests.common:2.0.2-SNAPSHOT @ /Users/konradwindszus/git/eclipse/m2e-core/org.eclipse.m2e.tests.common/.tycho-consumer-pom.xml
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-integration-test of goal org.eclipse.tycho:tycho-surefire-plugin:3.0.0:integration-test failed: Cannot resolve dependencies of MavenProject: org.eclipse.m2e:org.eclipse.m2e.tests.common:2.0.2-SNAPSHOT @ /Users/konradwindszus/git/eclipse/m2e-core/org.eclipse.m2e.tests.common/.tycho-consumer-pom.xml
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.tycho.DependencyResolutionException: Cannot resolve dependencies of MavenProject: org.eclipse.m2e:org.eclipse.m2e.tests.common:2.0.2-SNAPSHOT @ /Users/konradwindszus/git/eclipse/m2e-core/org.eclipse.m2e.tests.common/.tycho-consumer-pom.xml
    at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies (P2ResolverImpl.java:253)
    at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveTargetDependencies (P2ResolverImpl.java:130)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies (P2DependencyResolver.java:427)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies (P2DependencyResolver.java:389)
    at org.eclipse.tycho.surefire.AbstractTestMojo.createEclipseInstallation (AbstractTestMojo.java:835)
    at org.eclipse.tycho.surefire.AbstractTestMojo.execute (AbstractTestMojo.java:704)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.tycho.p2.util.resolution.ResolverException: See log for details
    at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve (ProjectorResolutionStrategy.java:129)
    at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve (AbstractResolutionStrategy.java:53)
    at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies (P2ResolverImpl.java:236)
    at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveTargetDependencies (P2ResolverImpl.java:130)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies (P2DependencyResolver.java:427)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies (P2DependencyResolver.java:389)
    at org.eclipse.tycho.surefire.AbstractTestMojo.createEclipseInstallation (AbstractTestMojo.java:835)
    at org.eclipse.tycho.surefire.AbstractTestMojo.execute (AbstractTestMojo.java:704)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
```

I am using the following Maven version:
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec
Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.1", arch: "aarch64", family: "mac"
```

The dependency is declared in https://github.com/eclipse-m2e/m2e-core/blob/9416e758afe1a405fe6616ce110e7d974e73858e/pom.xml#L418 but it is not clear to me which repository is supposed to resolve this dependency.

### PR DESCRIPTION
**Pull request by kwin**
support aarch64 in target platform
This closes #1046

### CODE REVIEW

**Comment by kwin** [comment]
Some tests fail though on Mac OS currently:

```
MavenBugsTest.testBuildStartTime:108 [Marker [on: /buildStartTime, id: 1, type: org.eclipse.jdt.core.buildpath_problem, attributes: [arguments: 1:org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17, categoryId: 10, classpathFileFormat: false, cycleDetected: false, id: 963, location: Build path, message: Unbound classpath container: 'JRE System Library [JavaSE-17]' in project 'buildStartTime', outputOverlappingSource: false, severity: 2, sourceId: JDT], created: 22/11/2022, 12:05], Marker [on: /buildStartTime, id: 2, type: org.eclipse.jdt.core.problem, attributes: [categoryId: 10, message: The project cannot be built until build path errors are resolved, severity: 2, sourceId: JDT], created: 22/11/2022, 12:05]] expected:<0> but was:<2>
  MemoryConsumptionTest.testImportLongBuildChain:75 Some poms were not imported as project expected:<[]> but was:<[/var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p16/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p47/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p46/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p30/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p32/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p18/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p15/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p13/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p19/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p14/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p44/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p28/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p45/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p31/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p8/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p35/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p7/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p29/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p20/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p33/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p6/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p49/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p48/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p17/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p34/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p5/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p39/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p4/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p23/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p38/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p24/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p2/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p40/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p21/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p37/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p3/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p22/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p36/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p41/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p9/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p1/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p12/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p27/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p43/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p10/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p26/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p42/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p0/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p11/pom.xml, /var/folders/f8/_3c0rvgd00n324sqjc8y_3wr0000gn/T/MemoryConsumptionTest7291265905945559411/p25/pom.xml]>
```

**Review by HannesWell — APPROVED** [review]
Looks good. Thank you.

**Comment by HannesWell** [comment]
> Some tests fail though on Mac OS currently:
> 

Do you want to investigate the failure and provide fixes? I only have Windows and Linux and can therefore can not help on Mac at all.

If the tests are not failing in the workspace and you want to debug them in the build, that should become simpler with the latest M2E snapshot in about 15min.
All you then have to do is to add the `debugPort=8000` property to the `m2e-core--build` launch and a break-point in your test should be hit automatically.

**Comment by kwin** [comment]
I won't have time for that soon, but you should really enable running those tests in GHA with all supported operating systems (#1080) otherwise they will easily be broken again on untested OS (even after doing a one time fix)

**Pull request merged**
