### PR TITLE
Create a single fake repo in the bundles private area

### PR DESCRIPTION
**Pull request by laeubi**
Fix https://github.com/eclipse-m2e/m2e-core/issues/927

### CODE REVIEW

**Comment by laeubi** [comment]
@HannesWell @mickaelistria any ideas? GH+Jenkins show different failures and all these don't seem directly related here (or I don't understand the connection ... )

**Comment by HannesWell** [comment]
> @HannesWell @mickaelistria any ideas? GH+Jenkins show different failures and all these don't seem directly related here (or I don't understand the connection ... )

Looks similar to the failures in https://github.com/eclipse-m2e/m2e-core/pull/931 and the master build is also failing with the same issue:
https://ci.eclipse.org/m2e/job/m2e/job/master/397/

Maybe it is related to that we use openjdk-latest (which is Java-19). I'm about to create a PR to check that.
Or it is the Tycho 3.0-SNAPSHOT. Besides that nothing changed since the last successful builds as far as I now.

**Comment by HannesWell** [comment]
> Maybe it is related to that we use openjdk-latest (which is Java-19). I'm about to create a PR to check that. Or it is the Tycho 3.0-SNAPSHOT. Besides that nothing changed since the last successful builds as far as I now.

Lets see what https://github.com/eclipse-m2e/m2e-core/pull/936 does.

**Review by HannesWell — COMMENTED** [review]
Regarding this change, it looks good to me.

I just wonder if it could be problematic if the file is used concurrently?

**Comment by laeubi** [comment]
@HannesWell thanks for the build fix. The file is only empty and I actually think we should be able to get rid of this completely but for now I'm fine with not getting spammed all the day ;-)

**Comment by HannesWell** [comment]
> @HannesWell thanks for the build fix. The file is only empty and I actually think we should be able to get rid of this completely but for now I'm fine with not getting spammed all the day ;-)

You're welcome. Sound good 👍🏽 I have to admit I usually don't monitor my temp-dir. But I agree it is annoying if the file-system is spammed.

**Comment by laeubi** [comment]
Well I don't really "monitor" the temp dir but as Linux has a single temp dir `/tmp` that is easily accessible (and that is cleared on restart) I often use this to download... well temporary stuff ... like test-cases, build-logs and so on, so having thousands(!) of folders there makes it really hard to find anything :-)

**Comment by HannesWell** [comment]
> Well I don't really "monitor" the temp dir but as Linux has a single temp dir `/tmp` that is easily accessible (and that is cleared on restart) I often use this to download... well temporary stuff ... like test-cases, build-logs and so on, so having thousands(!) of folders there makes it really hard to find anything :-)

Understand. 👍🏽 I'm often on Windows and therefore not so much used to activly use the temp-dir. But I would be annoyed as well if e.g. my Downloads folder would be spammed. :)

**Comment by laeubi** [comment]
> But I would be annoyed as well if e.g. my Downloads folder would be spammed. :)

I have recently delete around 3.000 fakerepo dirs after half of a developers day :-\

Even if users don't notice this, this also take up space and creates disk I/O ...

**Comment by sman-81** [comment]
> I have recently delete around 3.000 fakerepo dirs after half of a developers day :-\

same here

`rm -rf /tmp/fakerepo*` amongst my most frequently used commands these days ;)

**Pull request merged**
