### PR TITLE
Fixes for Bug 570372, Bug 570315

### PR DESCRIPTION
**Pull request by laeubi**
- NullPointerException when trying to edit instructions in target
definition editor
 - The latest contribution of m2e to SimRel 2021-03 M1 has bad licenses
and unsigned bundles

Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Please bump bundle (and probably also feature) version to 1.17.2

**Comment by laeubi** [comment]
Version was bumped before already!

**Comment by mickaelistria** [comment]
Versions were not bumped on the *ui* bundle yet since last release: https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.pde.ui/META-INF/MANIFEST.MF#L5

**Comment by mickaelistria** [comment]
Test failure is not related. Let's merge. Thanks!

**Pull request merged**
