### PR TITLE
[Build] improve snapshot deployment (remove <version>/latest and clear)

### PR DESCRIPTION
**Pull request by HannesWell**
With this PR I propose to
1. remove the 'latest' subfolder for the snapshot repo with a specific version to align better with snapshots/latest and releases.
The current `https://download.eclipse.org/technology/m2e/snapshots/1.19.1/latest/` would become `https://download.eclipse.org/technology/m2e/snapshots/1.19.1/`. Because there are no subversions or similar, the latest-subfolder has no advantage.

2. completely clear `download.e.o/tech/m2e/snapshots` before the snapshot-repo of a current master build is deployed.
 This way an old version repo is removed automatically once a new one is available.

3. inline only once used variables in the Jenkins file

@mickaelistria check you please check that the syntax is correct (I'm not a master of the linux shell).

### CODE REVIEW

**Comment by mickaelistria** [comment]
I have no objection here, however shouldn't the docs be updated as well? And also, what about even dropping the version part for snapshots?

**Comment by HannesWell** [comment]
> I have no objection here, however shouldn't the docs be updated as well?

I could not find those versioned-snapshot repos mentioned anywhere but I agree they should be.

> And also, what about even dropping the version part for snapshots?

I thought about that as well, but I think it is handy for those that urgently want a fix for a problem or a new feature (or so) and therefore want to use the current snapshots but in general want to use the releases.
Those users (that likely have `m2e/releases/latest` repo as available updatesite) can add the version-specific snapshot repo and get the snapshots until the next release.
Since that version-specific snapshot repo is deleted with the release they "fallback" to the releases repo and from now on get only the regular release updates. They likely get an error message that that version-specific repo is not available anymore (and likely will remove it) but they wont stay at the snapshot repo accidentally forever.

**Comment by HannesWell** [comment]
The [M2E's Jenkins Job `promote-snapshots-to-release `](https://ci.eclipse.org/m2e/job/promote-snapshots-to-release/) has to be updated accordingly since it promotes the version-specific repo.

**Comment by HannesWell** [comment]
I'm going to merge this now and will update the `promote-snapshots-to-release` job accordingly.
If we found the version-specific snapshot repos to be unnecessary we can still delete them later.

Furthermore I'm going to delete [M2E's Jenkins project `download-cleanup`](https://ci.eclipse.org/m2e/job/download-cleanup/) since it is obsolete. The downloads are cleaned up now and can be cleaned up via the web-interface in the future by moving artifacts-to-delete to archive and deleting them from there.

**Comment by HannesWell** [comment]
New deployment worked well. Old snapshot repos were deleted automatically and the current version specific one is at:
https://download.eclipse.org/technology/m2e/snapshots/1.19.2/

**Pull request merged**
